from pathlib import Path
import hashlib,json,re,subprocess,imageio_ffmpeg,math
out=Path('D:/07-GAMES/Firstlight/artifacts/local-life-20261003/normal-ui-rtx-03');r=json.loads((out/'REPORT.json').read_text());assert r['status']=='passed' and r['passed']==19 and r['failed']==0 and not r['errors'];ff=imageio_ffmpeg.get_ffmpeg_exe();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();source=out/'LOCAL_LIFE_NORMAL_UI.webm';assert sha(source)==r['video']['sha256']
full=out/'LOCAL_LIFE_NORMAL_UI.mp4';mobile=out/'MOBILE_LOCAL_LIFE.mp4';assert not full.exists() and not mobile.exists()
def command(name,args):
 p=subprocess.run([ff,'-hide_banner','-nostats','-n',*args],capture_output=True,text=True,encoding='utf-8',errors='replace');(out/(name+'.log')).write_text(p.stdout+'\n'+p.stderr,encoding='utf-8');assert p.returncode==0,(name,p.returncode,p.stderr[-1200:]);return p
def decode(path,name):
 p=command(name,['-i',str(path),'-map','0:v:0','-f','null','-','-progress','pipe:1']);pairs=dict(re.findall(r'^(\w+)=(.+)$',p.stdout,re.M));assert pairs.get('progress')=='end';fmt=re.search(r'Video: (.+)',p.stderr);duration=float(pairs['out_time_us'])/1e6;return {'file':path.name,'sha256':sha(path),'bytes':path.stat().st_size,'fully_decoded_frames':int(pairs['frame']),'decoded_seconds':duration,'stream':fmt.group(1) if fmt else None,'decode_exit_code':p.returncode,'decode_errors': [x for x in p.stderr.splitlines() if 'error' in x.lower()]}
command('CONVERT_FULL',['-i',str(source),'-map','0:v:0','-an','-c:v','libx264','-preset','fast','-crf','24','-threads','4','-pix_fmt','yuv420p','-movflags','+faststart',str(full)])
a=decode(source,'DECODE_SOURCE');b=decode(full,'DECODE_FULL');assert a['fully_decoded_frames']==b['fully_decoded_frames'] and abs(a['decoded_seconds']-b['decoded_seconds'])<.05
start=max(0,b['decoded_seconds']-65)
command('CONVERT_MOBILE',['-ss',str(start),'-i',str(full),'-t','65','-map','0:v:0','-an','-c:v','libx264','-preset','fast','-crf','24','-threads','4','-pix_fmt','yuv420p','-movflags','+faststart',str(mobile)])
c=decode(mobile,'DECODE_MOBILE');assert abs(c['decoded_seconds']-65)<.08
assert all(v['bytes']<100_000_000 and not v['decode_errors'] for v in [a,b,c])
receipt={'method':'Original Playwright whole-UI silent recording; MP4 conversion preserves decoded frame count and time, without changing frame rate or speed. Mobile is the final65s of the same recording, no synthetic/gameplay substitute. Both streams fully decoded by the bundled FFmpeg7.1.', 'original_report_sha256':sha(out/'REPORT.json'),'html_sha256':r['html_sha256'],'harness_sha256':r['harness_sha256'],'fixture_sha256':r['fixture_sha256'],'authoring_base_head':r['head'],'actual_renderer':r['renderer'],'normal_raf_checks':{'passed':r['passed'],'failed':r['failed'],'position_edits':r['position_edits'],'resource_grants':r['resource_grants'],'accelerated_ticks':r['accelerated_ticks']},'source':a,'full':b,'mobile':{**c,'start_in_full_seconds':start},'ffmpeg_executable':ff,'ffmpeg_sha256':sha(Path(ff)),'silent':True,'human_playtest':False,'gpu_measurement_scope':'Two600-interval Cosmos samples while video capture is enabled; headless desktop workload, not isolated GPU or whole-world qualification.'}
(out/'MEDIA_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8');print(json.dumps({k:receipt[k] for k in ['source','full','mobile']},indent=2))
