'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const data=require('../src/cosmos-campaign-data.js');
const trails=require('../src/realm-trails.js');
// Labelled UI boundary fixture. The separate rule tests own earned progress;
// this file tests real panel/action code against a deliberately strict caller.
function fixture(){
 const nodes=new Map(),sim={room:data.definition.room,state:{adventure:{revision:7},player:{x:3,z:-43},cosmosCampaign:{version:1,accepted:false,steps:[],choice:null,opened:false,claimed:false}}},calls=[],ctx={sim,active:'synthetic-ui-owner',revision:4};
 const H={definition:data.definition,eligible:()=>true,ready:s=>s.cosmosCampaign.steps.includes('verify-open-bearings'),at:(s,p)=>Math.hypot(s.state.player.x-p.x,s.state.player.z-p.z)<.1,available:s=>data.definition.steps.filter(p=>!s.cosmosCampaign.steps.includes(p.id)&&p.requires.every(id=>s.cosmosCampaign.steps.includes(id))&&(p.requiresSupports===undefined||data.completedSupports(s.cosmosCampaign.steps).length>=p.requiresSupports)&&(p.requiresConfiguredSupports===undefined||data.configuredSupports(s.cosmosCampaign.steps).length>=p.requiresConfiguredSupports))};
 const sandbox={RealmCosmosCampaign:H,RealmCosmosCampaignData:data,RealmTrails:trails,RealmTrailsUI:{approach:(s,p)=>({x:p.x,z:p.z})},document:{querySelector:k=>{if(!nodes.has(k))nodes.set(k,{textContent:'',hidden:false});return nodes.get(k);}},module:{exports:{}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/cosmos-campaign-ui.js'),'utf8'),sandbox);
 const rpg={sim,tab:'cosmos-campaign',quest:'story',api:{worldContext:()=>ctx,walkLocal:(x,z)=>calls.push({kind:'walk',x,z}),toast:text=>calls.push({kind:'toast',text}),cosmosCampaignCommand:(type,payload)=>{calls.push({kind:'command',type,payload:{...payload}});return{ok:false,error:'Boundary test refused; actual owner is not substituted.'};}},open:tab=>{rpg.tab=tab;calls.push({kind:'open',tab});},close:()=>calls.push({kind:'close'}),paint:()=>calls.push({kind:'paint'})};
 const ui=new sandbox.RealmCosmosCampaignUI.CosmosCampaignUI(rpg),act=(type,id='',binding=true)=>ui.action({dataset:{rpg:'cosmos-campaign-'+type,id,...(binding&&ui.binding?{binding:String(ui.binding.id),revision:String(ui.binding.revision)}:{})}});
 return{sim,ctx,calls,rpg,ui,act,H,api:sandbox.RealmCosmosCampaignUI,nodes};
}
function accepted(f,steps=[]){f.sim.state.cosmosCampaign.accepted=true;f.sim.state.cosmosCampaign.steps=steps.slice();}
function at(f,id){const p=data.definition.steps.find(s=>s.id===id);Object.assign(f.sim.state.player,{x:p.x,z:p.z});}
const command=f=>f.calls.filter(c=>c.kind==='command');
test('terms disclose exact fee, danger, alternatives and account before consent; panel grants nothing',()=>{const f=fixture(),before=JSON.stringify(f.sim.state);const p=f.ui.panel();assert.equal(p.title,'The Open Confluence');for(const term of['50 XP','20 sunmarks','5 ore','4 timber','3 meadow fibre','2 crystal','84 health','168 health','Any two','Public mechanical account','bounded testimony'])assert.ok(p.html.includes(term),term);assert.ok(p.html.includes('data-rpg="cosmos-campaign-accept"'));assert.equal(JSON.stringify(f.sim.state),before);assert.equal(command(f).length,0);});
test('accept intent uses current active and revision; reading and walking never grant acceptance',()=>{const f=fixture(),before=JSON.stringify(f.sim.state);f.ui.panel();f.act('walk','giver');assert.equal(command(f).length,0);assert.ok(f.calls.some(c=>c.kind==='walk'&&c.x===3&&c.z===-43));f.act('accept');assert.equal(command(f).length,1);assert.deepEqual(command(f)[0].payload,{quest:data.definition.id,expectedRevision:7,expectedActive:'synthetic-ui-owner'});assert.equal(JSON.stringify(f.sim.state),before);});
test('old panel binding cannot command after movement, revision, character or context replacement',()=>{for(const change of[f=>f.sim.state.player.x+=.02,f=>f.sim.state.adventure.revision++,f=>f.ctx.active='other-owner',f=>f.ctx.revision++,f=>f.ctx.sim={...f.sim}]){const f=fixture();f.ui.panel();change(f);f.act('accept');assert.equal(command(f).length,0);assert.ok(f.calls.some(c=>c.kind==='toast'));}});
test('routes contain available physical objectives and no fake completion marker',()=>{const f=fixture();assert.equal(f.api.routePoints(f.sim).length,0);accepted(f);const points=f.api.routePoints(f.sim);assert.deepEqual(Array.from(points,p=>p.id),['read-local-cost']);assert.equal(points[0].mark,'C1');assert.equal(points[0].cosmosCampaign,true);f.sim.room=null;assert.equal(f.api.routePoints(f.sim).length,0);});
test('configure sends exact declared setting only at an available real fixture',()=>{const f=fixture();accepted(f,['read-local-cost']);at(f,'assist-material');f.ui.panel();f.act('configure','assist-material');assert.equal(command(f).length,1);assert.equal(command(f)[0].type,'configure');assert.equal(command(f)[0].payload.setting,'seat-tested-brace');assert.equal(command(f)[0].payload.step,'assist-material');assert.deepEqual(f.sim.state.cosmosCampaign.steps,['read-local-cost']);f.sim.state.player.x+=1;f.ui.panel();f.act('configure','assist-material');assert.equal(command(f).length,1);});
test('missing work or a forged defeat action cannot command its completion from the UI',()=>{const f=fixture();accepted(f);at(f,'disable-central-link');f.ui.panel();f.act('configure','disable-central-link');f.act('defeat','guardian-settled');assert.equal(command(f).length,0);});
test('choice preview leaves ledger unchanged; explicit confirm binds exact choice and checkpoint',()=>{const f=fixture();accepted(f,['release-west-feed','release-east-feed','guardian-settled','disable-central-link']);at(f,'accountability');const before=JSON.stringify(f.sim.state);f.ui.panel();f.act('review','bounded-account');assert.equal(command(f).length,0);assert.equal(JSON.stringify(f.sim.state),before);assert.equal(f.ui.pending.choice,'bounded-account');assert.ok(f.ui.panel().html.includes('cosmos-campaign-confirm'));f.act('confirm','bounded-account');assert.equal(command(f).length,1);assert.equal(command(f)[0].type,'choose');assert.equal(command(f)[0].payload.choice,'bounded-account');assert.equal(f.ui.pending,null);assert.equal(JSON.stringify(f.sim.state),before);});
test('changed preview or alternate confirmation cannot record consent',()=>{for(const change of[f=>f.sim.state.player.x+=.02,f=>f.ctx.active='other-owner',f=>f.sim.state.adventure.revision++]){const f=fixture();accepted(f,['disable-central-link']);at(f,'accountability');f.ui.panel();f.act('review','public-record');change(f);f.ui.panel();f.act('confirm','public-record');assert.equal(command(f).length,0);}const f=fixture();accepted(f,['disable-central-link']);at(f,'accountability');f.ui.panel();f.act('review','public-record');f.ui.panel();f.act('confirm','bounded-account');assert.equal(command(f).length,0);});
test('cancel and stale tick preserve undecided consent; completed tracking returns to story',()=>{const f=fixture();accepted(f,['disable-central-link']);at(f,'accountability');f.ui.panel();f.act('review','public-record');f.act('cancel');assert.equal(f.ui.pending,null);assert.equal(command(f).length,0);f.act('review','public-record');f.sim.state.adventure.revision++;f.ui.tick();assert.equal(f.ui.pending,null);f.rpg.quest='cosmos-campaign';f.sim.state.cosmosCampaign.claimed=true;f.ui.tick();assert.equal(f.rpg.quest,'story');});
test('prepared-support tracker makes two-support gate legible without advancing history',()=>{const f=fixture();accepted(f,['read-local-cost']);f.rpg.quest='cosmos-campaign';const before=JSON.stringify(f.sim.state);f.ui.tick();assert.match(f.nodes.get('#tracked-progress').textContent,/0 prepared · 0 reconfigured/);assert.equal(JSON.stringify(f.sim.state),before);assert.equal(command(f).length,0);});
test('missing-prerequisite guidance names the actual separately owned comparator',()=>{const f=fixture();f.H.eligible=()=>false;const page=f.ui.page('cosmos-campaign');assert.ok(page.html.includes(trails.definition(data.definition.prerequisite).title));assert.ok(page.html.includes('Two Stations, One Honest Bearing'));assert.ok(!page.html.includes('Split Bearing'));assert.equal(command(f).length,0);});
test('the RPG page adapter filters unrelated tabs without rebinding a confirmation',()=>{const f=fixture();assert.equal(f.ui.binding,null);assert.equal(f.ui.page('equipment'),null);assert.equal(f.ui.binding,null);assert.equal(f.ui.page('cosmos-campaign').title,'The Open Confluence');assert.ok(f.ui.binding);});
