'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const R=path.resolve(process.env.FIRSTLIGHT_ROOT||path.join(__dirname,'..')),E=require(R+'/src/engine.js'),data=require('../src/cosmos-campaign-data.js');
// Labelled staged-art fixture: real production matrix/meshes, prospective
// 4.77 slab height and an explicit refusing/non-progressing rules facade.
function fixture(){const sim={room:data.definition.room,state:{cosmosCampaign:{accepted:true,steps:[],choice:null,opened:false}}},enemies=new Set(),witnesses=[];const facade={owned:(s,e)=>enemies.has(e),canDamage:(s,e)=>!s.paused&&enemies.has(e),runtime:()=>({witnesses})};const context={RealmEngine:E,RealmCosmos:{height:()=>4.77},RealmCosmosCampaign:facade,RealmCosmosCampaignData:data,module:{exports:{}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/cosmos-campaign-art.js'),'utf8'),context);return{sim,enemies,witnesses,art:context.module.exports};}
const empty=()=>({box:[],octa:[],disc:[],round:[]}),all=o=>Object.values(o).flat();
function vertices(kind,p){const geom=E.geometry(kind),out=[];for(let i=0;i<geom.length;i+=6)out.push(E.M.transform(p.m,Array.from(geom.slice(i,i+3))));return out;}
function warning(f,id,strike,yaw=0){const spec=data.definition.enemies.find(e=>e.id===id),e={...spec,cosmosCampaign:data.definition.id,maxHP:spec.hp,mode:'windup',yaw,strike};f.enemies.add(e);const out=empty();assert.ok(f.art.drawEnemy(out,f.sim,e));return{e,out,parts:Object.entries(out).flatMap(([kind,ps])=>ps.filter(p=>p.cosmosCampaignTelegraph).map(p=>({kind,p}))) };}
function local(s,v){const dx=v[0]-s.x,dz=v[2]-s.z;return{x:dx*Math.cos(s.yaw)-dz*Math.sin(s.yaw),z:dx*Math.sin(s.yaw)+dz*Math.cos(s.yaw)};}
test('unaccepted or wrong-scene artwork creates no scene items or saved work',()=>{const f=fixture();for(const change of[()=>f.sim.state.cosmosCampaign.accepted=false,()=>{f.sim.state.cosmosCampaign.accepted=true;f.sim.room=null;}]){change();const before=JSON.stringify(f.sim),o=empty();f.art.draw(o,f.sim);assert.equal(all(o).length,0);assert.equal(JSON.stringify(f.sim),before);}});
test('original apparatus transforms are finite, collision-free and leave all state unchanged',()=>{const f=fixture(),before=JSON.stringify(f.sim),o=empty();f.art.draw(o,f.sim);assert.ok(all(o).length>50);assert.ok(all(o).length<150,'bounded procedural item count');for(const p of all(o)){assert.equal(p.cameraSolid,false);assert.equal(p.appearanceOnly,true);assert.ok(p.p.every(Number.isFinite));assert.ok(Array.from(p.m).every(Number.isFinite));}assert.equal(JSON.stringify(f.sim),before);});
test('ring rims remain centred on the frozen contact frame at rotated world positions',()=>{for(const yaw of[0,.7,Math.PI/2]){const f=fixture(),s={kind:'annulus',x:54,z:-44,yaw,innerRadius:1.8,outerRadius:4.6},w=warning(f,'cosmos-still-meridian-guardian-v1',s);assert.equal(w.parts.length,192);for(const {kind,p}of w.parts)for(const v of vertices(kind,p)){const a=local(s,v),radius=Math.hypot(a.x,a.z),inner=p.cosmosCampaignPart.startsWith('quiet-inner-rim');assert.ok(radius<(inner?s.innerRadius:s.outerRadius)+1e-5);assert.ok(radius>(inner?s.innerRadius:s.outerRadius)-.10);assert.ok(v[1]>4.85,'warning above the paving');}}});
test('released outer feed visibly changes only supplied future-frame radius',()=>{const f=fixture(),s={kind:'annulus',x:54,z:-44,yaw:.4,innerRadius:1.8,outerRadius:3.2},w=warning(f,'cosmos-still-meridian-guardian-v1',s);const before=JSON.stringify(s);for(const {kind,p}of w.parts.filter(v=>v.p.cosmosCampaignPart.startsWith('danger-outer-rim')))for(const v of vertices(kind,p))assert.ok(Math.hypot(v[0]-54,v[2]+44)<3.2+1e-5);assert.equal(JSON.stringify(s),before);});
test('asymmetrically clipped cross arms render within each actual locked extent after rotation',()=>{for(const yaw of[0,.6,Math.PI/2]){const f=fixture(),s={kind:'cross',x:54,z:-44,yaw,halfWidth:.55,arms:[{axis:0,negative:2.1,positive:5.8},{axis:Math.PI/2,negative:4,positive:1.2}]},w=warning(f,'cosmos-still-meridian-guardian-v1',s);assert.equal(w.parts.length,16);for(const {kind,p}of w.parts)for(const v of vertices(kind,p)){const a=local(s,v);assert.ok(s.arms.some(arm=>{const side=a.x*Math.cos(arm.axis)-a.z*Math.sin(arm.axis),forward=a.x*Math.sin(arm.axis)+a.z*Math.cos(arm.axis);return Math.abs(side)<=s.halfWidth+1e-5&&forward>=-arm.negative-1e-5&&forward<=arm.positive+1e-5;}));}}});
test('released transverse feed produces one actual warned arm without inventing a second',()=>{const f=fixture(),s={kind:'cross',x:54,z:-44,yaw:0,halfWidth:.55,arms:[{axis:0,negative:2.1,positive:4}]},w=warning(f,'cosmos-still-meridian-guardian-v1',s);assert.equal(w.parts.length,8);for(const {kind,p}of w.parts)for(const v of vertices(kind,p))assert.ok(Math.abs(v[0]-s.x)<=.55+1e-5);});
test('locked Optical line warning honors its clipped length with no protruding decoration',()=>{for(const yaw of[0,.3,Math.PI/2]){const f=fixture(),s={kind:'line',x:36,z:-40,yaw,length:2.7,halfWidth:.55},w=warning(f,'cosmos-optical-reclaimer-v1',s);assert.equal(w.parts.length,8);for(const {kind,p}of w.parts)for(const v of vertices(kind,p)){const a=local(s,v);assert.ok(Math.abs(a.x)<=.55+1e-5);assert.ok(a.z>=-1e-5&&a.z<=2.7+1e-5);}}});
test('unowned, settled or non-live bodies cannot impersonate an active warning',()=>{const f=fixture(),e={...data.definition.enemies[1],cosmosCampaign:data.definition.id,mode:'windup',strike:{kind:'annulus',x:54,z:-44,yaw:0,innerRadius:1.8,outerRadius:4.6}},o=empty();assert.equal(f.art.drawEnemy(o,f.sim,e),false);assert.equal(all(o).length,0);f.enemies.add(e);f.sim.state.cosmosCampaign.steps.push(e.defeatStep);assert.equal(f.art.drawEnemy(o,f.sim,e),false);assert.equal(all(o).length,0);});
test('retained support settings/account change appearance without creating completed facts',()=>{const f=fixture();Object.assign(f.sim.state.cosmosCampaign,{steps:['assist-material','configure-material','open-confluence','accountability'],choice:'bounded-account',opened:true});const before=JSON.stringify(f.sim),o=empty();f.art.draw(o,f.sim);assert.ok(all(o).some(p=>p.cosmosCampaignPart==='independent-local-setting'));assert.ok(all(o).some(p=>p.cosmosCampaignPart==='bounded-statement-folder'));assert.ok(all(o).some(p=>p.cosmosCampaignOpened===true));assert.equal(JSON.stringify(f.sim),before);});
test('opening a paused workspace preserves the owned body and its already locked warning',()=>{const f=fixture();f.sim.paused=true;const s={kind:'annulus',x:54,z:-44,yaw:0,innerRadius:1.8,outerRadius:4.6},spec=data.definition.enemies[1],e={...spec,cosmosCampaign:data.definition.id,maxHP:spec.hp,mode:'windup',yaw:0,strike:s};f.enemies.add(e);const o=empty();assert.ok(f.art.drawEnemy(o,f.sim,e));assert.ok(all(o).some(p=>p.cosmosCampaignPart==='connected-meridian-crown'));assert.ok(all(o).some(p=>p.cosmosCampaignTelegraph));});
test('very short clipped warnings keep every cap inside the supplied frame',()=>{for(const length of[.026,.03,.04,.1])for(const yaw of[0,.3,Math.PI/2]){const f=fixture(),s={kind:'line',x:36,z:-40,yaw,length,halfWidth:.55},w=warning(f,'cosmos-optical-reclaimer-v1',s);assert.equal(w.parts.length,8);for(const {kind,p}of w.parts)for(const v of vertices(kind,p)){const a=local(s,v);assert.ok(a.z>=-1e-5&&a.z<=length+1e-5,JSON.stringify({length,yaw,forward:a.z}));assert.ok(Math.abs(a.x)<=.55+1e-5);}}});
