'use strict';
// Bounded three-case actual installed command-earned journey; no direct state grants.
const test=require('node:test'),assert=require('node:assert/strict'),J=require('../tools/earth-wild-signs-journey/earned_wild_signs.cjs');
for(const c of [{variant:'blade',route:'south',reverse:false,resolution:'signed-loop'},{variant:'bow',route:'south',reverse:true,resolution:'cleared-pocket',refuseObservation:true},{variant:'veteran',route:'north',reverse:false,resolution:'cleared-pocket',refuseClearance:true}])test(c.variant+' earns actual supplied load, '+c.resolution+' and separate fee',()=>{
 const h=J.create(c.variant,c.route),before=J.protectedFacts(h.sim.state),initial=J.economy(h.sim.state),home=J.copy(h.sim.returnPos);h.earnLoad();assert.ok(h.sim.state.localLife.records[J.CD.ID].claimed);h.cold();h.toInvitation();h.clueReads(c.reverse);const ticket=h.observe(c.refuseObservation);assert.equal(J.O.validateObservation(h.grazerContext(),ticket).ok,false);h.response(c.resolution);
 if(c.resolution==='cleared-pocket'){h.clearPest(c.refuseClearance);if(c.variant==='bow')assert.ok(h.metrics.projectileShots>0);if(c.variant==='veteran')assert.ok(h.metrics.companionStrikes>0,'actual retained companion assists in the earned encounter');h.toSela();}else{assert.equal(h.pest(),undefined);h.walkMany([J.D.evidence[1],J.D.evidence[0],{x:-148,z:-64},{x:-125,z:-57},{x:-125,z:-44},{x:-109,z:-28},J.D.giver]);}
 h.payout();const expected=J.copy(initial);expected.coins+=8;expected.inventory.wood+=2;expected.inventory.fiber+=5;assert.deepEqual(J.economy(h.sim.state),expected);assert.deepEqual(J.protectedFacts(h.sim.state),before);assert.deepEqual(h.sim.returnPos,home);assert.deepEqual(h.sim.worldTrip.home,home);assert.equal(h.sim.state.earthWildSigns.resolution,c.resolution);assert.equal(h.sim.state.earthWildSigns.cleared,c.resolution==='cleared-pocket');assert.equal(h.sim.state.earthWildSigns.claimed,true);h.cold();assert.equal(h.pest(),undefined);assert.ok(h.signsCommand('claim').duplicate);assert.deepEqual(J.protectedFacts(h.sim.state),before);assert.deepEqual(J.economy(h.sim.state),expected);assert.ok(J.W.leave(h.sim).ok);assert.deepEqual(h.sim.state.player,home);assert.ok(h.save(h.sim.snapshot()).ok);h.assertReceipts();
 assert.equal(h.metrics.positionEdits,0);assert.equal(h.metrics.inventoryGrants,0);assert.equal(h.metrics.hpEdits,0);assert.equal(h.metrics.plantedDefeats,0);assert.ok(h.metrics.workerDistance>100&&h.metrics.playerDistance>400);assert.equal(h.metrics.arrivalIds.length,J.CD.required(h.sim.state.localLife.records[J.CD.ID]).length);assert.ok(['lower','browse','recover','walk'].every(p=>h.metrics.observationPhases.includes(p)));console.log('WILD_SIGNS_EARNED_JOURNEY '+JSON.stringify(h.metrics));
});
test.after(()=>{const b=J.binding();assert.equal(b.inputsUnchanged,true);assert.equal(b.sourceHeadAfter,b.sourceHead);console.log('JOURNEY_INPUT_BINDINGS '+JSON.stringify(b));});
