/* CPU projection/binding tests. Prior claimed facts, poses, actual roster and synthetic history and supplied clipped frames are explicit synthetic unit setup.
 * The homecoming command observer refuses all writes. The fresh-kit regression
 * alone dispatches the actual legacy start command through its actual UI owner.
 * UI constructors are bypassed for CPU tests; no earned/native/installed AI proof. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const R=path.resolve(process.env.FIRSTLIGHT_ROOT||path.join(__dirname,'..'));
const RULES=path.join(R,'src');
const load=n=>require(path.join(R,'src',n)),C=load('core.js'),A=load('adventure.js'),E=load('engine.js'),W=load('world-foundations.js'),RT=load('realm-trails.js'),ES=load('earth-story.js'),EE=load('earth-expedition.js'),HC=load('hell-campaign.js'),HV=load('heaven-campaign.js'),AT=load('atlantis-campaign.js'),CC=load('cosmos-campaign.js'),H=require(RULES+'/earth-homecoming.js'),DATA=require(RULES+'/earth-homecoming-data.js'),D=H.definition,copy=structuredClone;
const readFiles=['core.js','adventure.js','adventure-ui.js','starter-ui.js','starter.js','road.js','arsenal.js','combat.js','engine.js','world.js','creative.js','world-foundations.js','world-atlantis-earth.js','rpg-ui.js','realm-trails-ui.js','world-foundations-ui.js','earth-story.js','earth-expedition.js','hell-campaign.js','heaven-campaign.js','atlantis-campaign.js','cosmos-campaign.js'].map(n=>R+'/src/'+n).concat([RULES+'/earth-homecoming.js',RULES+'/earth-homecoming-data.js']);
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),hashes=Object.fromEntries(readFiles.map(p=>[p,sha(p)]));
// These are actual production methods, with only constructor-created DOM omitted.
const legacy={RealmCore:C,RealmAdventure:A,RealmRoad:load('road.js'),RealmArsenal:load('arsenal.js'),RealmCombat:load('combat.js'),RealmStarter:load('starter.js'),document:{querySelector:()=>null}};
for(const name of['adventure-ui.js','starter-ui.js','rpg-ui.js'])vm.runInNewContext(fs.readFileSync(R+'/src/'+name,'utf8'),legacy);
function closeActualWorkspace(f){
 f.rpg.dialog={open:true,close(){this.open=false;f.calls.push({kind:'actual-workspace-close'});}};
 f.rpg.wasPaused=f.sim.paused;f.sim.paused=true;
 f.rpg.api.clearKeys=()=>f.calls.push({kind:'clear-keys'});f.rpg.api.focusWorld=()=>f.calls.push({kind:'focus-world'});
 legacy.RealmRPGUI.RPGUI.prototype.close.call(f.rpg);
 assert.equal(f.rpg.dialog.open,false);assert.equal(f.rpg.tab,'earth-homecoming');
}
function oldAdventure(f){
 const ui=Object.create(legacy.RealmAdventureUI.AdventureUI.prototype);ui.sequence=0;ui.intent=null;
 ui.api={sim:()=>f.sim,save:()=>{f.calls.push({kind:'legacy-save-observer'});return{ok:true};},changed:()=>f.calls.push({kind:'legacy-changed'}),toast:text=>f.calls.push({kind:'legacy-toast',text}),audio:()=>null,panel:()=>null,openPanel:panel=>f.calls.push({kind:'legacy-panel',panel})};return ui;
}
function oldStarter(f){
 Object.defineProperty(f.rpg,'state',{configurable:true,get:()=>f.sim.state.adventure});
 const ui=Object.create(legacy.RealmStarterUI.StarterUI.prototype);ui.rpg=f.rpg;return ui;
}
function seed(){
 const raw=C.validate(JSON.parse(fs.readFileSync(R+'/docs/evidence/world-production-2026-10-03/captures/returning-fit-final-01/FINAL_WORLD.json')));
 raw.adventure.earthStory={...ES.fresh(),accepted:true,steps:ES.ROUTES.find(r=>r.id==='quarry').steps.slice(),dispatch:'quarry',arrived:true,claimed:true};raw.earthExpedition={...EE.fresh(),story:{accepted:true,branch:'managed-coppice',steps:EE.definition.steps.map(s=>s.id),claimed:true}};
 Object.assign(raw.journeys.realms.earthlands,{counter:1,lastClaim:1,firstClaimed:true,active:null});
 for(const owner of[HC,HV,AT,CC]){const id=owner.definition.prerequisite,d=RT.definition(id),r=raw.realmTrails.records[id];r.accepted=true;r.claimed=true;r.steps=RT.required(d);if(d.escort)r.checkpoint=d.escort.route.length-1;for(const s of d.steps.filter(s=>s.instrument&&r.steps.includes(s.id)))r.settings[s.id]=s.instrument.target;}
 raw.hellCampaign={...HC.fresh(),accepted:true,steps:HC.definition.steps.filter(s=>!s.optional).map(s=>s.id),choice:'license',claimed:true};raw.heavenCampaign={...HV.fresh(),accepted:true,steps:HV.definition.steps.filter(s=>!s.optional).map(s=>s.id),choice:'broadened-activation',claimed:true};raw.atlantisCampaign={...AT.fresh(),accepted:true,steps:AT.required({approach:'lower'}),approach:'lower',choice:'limited',claimed:true};const opts=new Set(['assist-material','assist-living','configure-material','configure-living']);raw.cosmosCampaign={...CC.fresh(),accepted:true,steps:CC.definition.steps.filter(s=>!s.optional||opts.has(s.id)).map(s=>s.id),choice:'public-record',opened:true,claimed:true};return H.validateWorld(raw);
}
function fixture(raw=seed()){
 const sim=new C.Simulation(raw);sim.state.earthHomecoming=H.validate(raw.earthHomecoming);const nodes=new Map(),calls=[],ctx={sim,active:'synthetic-projection-owner',revision:4};
 const base={RealmEarthHomecoming:H,RealmEarthHomecomingData:DATA,RealmCore:C,RealmEngine:E,RealmWorldFoundations:W,RealmEarthStory:ES,RealmEarthExpedition:EE,RealmHellCampaign:HC,RealmHeavenCampaign:HV,RealmAtlantisCampaign:AT,RealmCosmosCampaign:CC,RealmTrails:RT};
 const uctx={...base,document:{querySelector:k=>{if(!nodes.has(k))nodes.set(k,{textContent:'',hidden:false});return nodes.get(k);}},module:{exports:{}}};vm.runInNewContext(fs.readFileSync(R+'/src/earth-homecoming-ui.js','utf8'),uctx);
 const actx={...base,module:{exports:{}}};vm.runInNewContext(fs.readFileSync(R+'/src/earth-homecoming-art.js','utf8'),actx);
 const rpg={sim,quest:'story',tab:'earth-homecoming',api:{worldContext:()=>ctx,toast:text=>calls.push({kind:'toast',text}),walkLocal:(x,z)=>calls.push({kind:'walk',x,z}),earthHomecomingCommand:(type,payload)=>{calls.push({kind:'command',type,payload:{...payload}});return{ok:false,error:'Synthetic UI boundary refuses every save; no earned action.'};}},open:tab=>{rpg.tab=tab;calls.push({kind:'open',tab});},close:()=>calls.push({kind:'close'}),paint:()=>calls.push({kind:'paint'})};
 const ui=new uctx.RealmEarthHomecomingUI.EarthHomecomingUI(rpg),action=(type,id='',bound=true)=>ui.action({dataset:{rpg:'earth-homecoming-'+type,id,...(bound&&ui.binding?{binding:String(ui.binding.id),revision:String(ui.binding.revision)}:{})}});
 const place=p=>{sim.room=p.room;sim.returnPos=p.room?{x:11,z:9,yaw:0}:null;sim.state.player={x:p.x,z:p.z,yaw:0};assert.ok(H.at(sim,p));};
 return{sim,calls,ctx,nodes,rpg,ui,action,place,api:uctx.module.exports,art:actx.module.exports};
}
const step=id=>D.steps.find(p=>p.id===id),commands=f=>f.calls.filter(c=>c.kind==='command'),empty=()=>({box:[],octa:[],round:[],disc:[]}),parts=o=>Object.entries(o).flatMap(([kind,items])=>items.map(p=>({kind,p}))),all=o=>parts(o).map(v=>v.p);
function accepted(f,last=''){const ss=last?D.steps.filter(s=>!s.optional).slice(0,D.steps.filter(s=>!s.optional).findIndex(s=>s.id===last)+1).map(s=>s.id):[];f.sim.state.earthHomecoming=H.validate({version:1,accepted:true,steps:ss,choice:ss.includes('aftermath')?'public-watch':null,claimed:false});}
function actor(f){accepted(f,'challenge-regent');f.place(step('challenge-regent'));A.syncScene(f.sim);const e=A.runtime(f.sim).enemies.find(a=>a.id===D.enemy.id);assert.ok(e,'actual installed roster supplies the actor');assert.ok(H.owned(f.sim,e));return e;}
function vertices(kind,p){const g=E.geometry(kind),out=[];for(let i=0;i<g.length;i+=6)out.push(E.M.transform(p.m,Array.from(g.slice(i,i+3))));return out;}
function local(s,v){const dx=v[0]-s.x,dz=v[2]-s.z;return{x:dx*Math.cos(s.yaw)-dz*Math.sin(s.yaw),z:dx*Math.sin(s.yaw)+dz*Math.cos(s.yaw)};}

test('unaccepted terms give the objective, exact fixed fee, signals and ordinary return before consent',()=>{const f=fixture();f.place(D.giver);const before=JSON.stringify(f.sim.state),p=f.ui.page('earth-homecoming');for(const s of['50 XP','20 sunmarks','4 ore','4 timber','3 fibre','1 crystal','168 health','1.85 seconds','Brace (3)','quiet center','wider network survives','Oren','Vessa','Merren'])assert.ok(p.html.includes(s),s);assert.ok(p.html.includes('earth-homecoming-accept'));assert.equal(JSON.stringify(f.sim.state),before);assert.equal(commands(f).length,0);});
test('every signal discloses the actual fixed geometry and warning/recovery terms',()=>{const f=fixture(),html=f.ui.panel().html;for(const term of['4 paces long, 2.2 wide','11 paces long, 1.1 wide','1.45 seconds of warning','1.85 seconds of warning','2.4 seconds of recovery','2.6 seconds of recovery','ring reaches 3.2','inner 1.5 paces','1.6 seconds of warning','Each strike lands once'])assert.ok(html.includes(term),term);});
test('junction defense advice respects the actual lack of opaque cover within every possible contact envelope',()=>{
 const d=W.definition(D.room),margin=.24,n=H.patterns['false-shelter'];
 const envelope=Math.max(Math.hypot(n.length+margin,n.halfWidth+margin),H.patterns['closing-ring'].outerRadius+margin);
 const nearest=Math.min(...d.solids.map(p=>Math.hypot(Math.max(0,Math.abs(p.x-D.enemy.x)-p.w/2-margin),Math.max(0,Math.abs(p.z-D.enemy.z)-p.d/2-margin))));
 assert.ok(nearest>envelope,'no actual opaque solid can shield this anchored encounter');
 const f=fixture(),html=f.ui.panel().html;
 assert.doesNotMatch(D.danger,/cover/i);assert.doesNotMatch(html,/use existing cover/);
 assert.match(html,/Step aside or into the quiet center, use Brace, or withdraw beyond his reach/);
 assert.ok(html.includes('Brace (3)')&&html.includes('1.85 seconds'),'real warning and guard options remain visible');
});
test('missing prerequisites use actual titles and places, including separately claimed Open Confluence',()=>{const f=fixture(H.validateWorld(C.fresh())),p=f.ui.panel();for(const owner of[EE,HC,HV,AT,CC])assert.ok(p.html.includes(owner.definition.title));assert.ok(p.html.includes(RT.definition('cosmos-split-bearing-v1').title));assert.ok(p.html.includes('Oren · Firstlight workshop'));assert.ok(p.html.includes('Teren · Three Lamps'));assert.ok(!p.html.includes('cosmos-confluence-paid'));assert.ok(!p.html.includes('earth-homecoming-accept'));assert.equal(f.api.prerequisites(f.sim.state).length,12);});
test('reading and actual workspace close leave ineligible fresh interactions to older owners in every tab/quest combination',()=>{
 for(const[tab,quest]of[['earth-homecoming','story'],['equipment','earth-homecoming'],['earth-homecoming','earth-homecoming'],['equipment','story']]){
  const f=fixture(H.validateWorld(C.fresh()));f.place(D.giver);const before=JSON.stringify(f.sim.state);
  f.ui.open();const page=f.ui.panel();assert.ok(page.html.includes('Finish these accounts before accepting'));assert.equal(f.api.prerequisites(f.sim.state).length,12);assert.ok(!page.html.includes('data-rpg="earth-homecoming-accept"'));
  closeActualWorkspace(f);f.rpg.tab=tab;f.rpg.quest=quest;
  assert.equal(f.ui.point(),null);assert.equal(f.ui.context(),null);assert.equal(f.ui.interact(),false);assert.equal(commands(f).length,0);assert.equal(JSON.stringify(f.sim.state),before);
 }
});
test('fresh real Core after reading and closing homecoming reaches the actual initial-kit command',()=>{
 const f=fixture(H.validateWorld(C.fresh()));f.place(D.giver);const homeBefore=JSON.stringify(f.sim.state.earthHomecoming),stateBefore=JSON.stringify(f.sim.state);
 assert.equal(f.sim.state.adventure.started,false);f.ui.open();f.ui.panel();closeActualWorkspace(f);
 assert.equal(JSON.stringify(f.sim.state),stateBefore);const old=oldAdventure(f);
 assert.equal(old.context(),'Take Oren’s expedition supplies');assert.equal(f.ui.interact(),false);assert.equal(old.interact(),true);
 assert.equal(f.sim.state.adventure.started,true);assert.deepEqual(f.sim.state.adventure.owned,['trail_blade','travel_coat']);assert.equal(f.sim.state.adventure.equipment.weapon,'trail_blade');
 assert.equal(f.calls.filter(c=>c.kind==='legacy-save-observer').length,1);assert.equal(f.calls.filter(c=>c.kind==='legacy-changed').length,1);assert.equal(commands(f).length,0);assert.equal(JSON.stringify(f.sim.state.earthHomecoming),homeBefore);
});
test('after the real initial kit, unreadable-for-acceptance homecoming does not intercept the actual starter/workbench owner',()=>{
 const f=fixture(H.validateWorld(C.fresh()));f.place(D.giver);f.ui.open();f.ui.panel();closeActualWorkspace(f);assert.equal(f.ui.interact(),false);assert.equal(oldAdventure(f).interact(),true);
 const starter=oldStarter(f),before=JSON.stringify(f.sim.state);f.rpg.quest='earth-homecoming';f.rpg.tab='earth-homecoming';
 assert.equal(H.eligible(f.sim.state),false);assert.equal(f.ui.point(),null);assert.equal(f.ui.context(),null);assert.equal(f.ui.interact(),false);
 assert.equal(starter.context(),'E · Oren: supplies, rewards & workbench');assert.equal(starter.interact(),true);assert.equal(f.rpg.tab,'starter');assert.equal(JSON.stringify(f.sim.state),before);assert.equal(commands(f).length,0);
 const old=oldAdventure(f);assert.equal(old.context(),'Oren’s workbench · bows, gems & practice');assert.equal(old.interact(),true);assert.equal(f.calls.at(-1).panel,'armory');assert.equal(JSON.stringify(f.sim.state),before);
});
test('eligible unaccepted and accepted physical actions remain reachable from either current tab or quest',()=>{
 for(const[tab,quest]of[['earth-homecoming','story'],['equipment','earth-homecoming']]){
  const f=fixture();f.place(D.giver);f.rpg.tab=tab;f.rpg.quest=quest;assert.equal(H.eligible(f.sim.state),true);const before=JSON.stringify(f.sim.state);
  assert.equal(f.ui.point().id,'giver');assert.match(f.ui.context(),/Oren/);assert.equal(f.ui.interact(),true);assert.equal(f.rpg.tab,'earth-homecoming');assert.equal(JSON.stringify(f.sim.state),before);assert.equal(commands(f).length,0);
  accepted(f);f.place(step('bridge-record'));f.rpg.tab=tab;f.rpg.quest=quest;assert.equal(f.ui.point().id,'bridge-record');assert.equal(f.ui.context(),'E · '+step('bridge-record').name);assert.equal(f.ui.interact(),true);assert.equal(commands(f).length,0);
  f.rpg.tab='equipment';f.rpg.quest='story';assert.equal(f.ui.point(),null);assert.equal(f.ui.context(),null);assert.equal(f.ui.interact(),false);
 }
});
test('accepted unpaid and claimed recognition retains both aftermaths and actual home/bridge gates across tabs and trackers',()=>{
 for(const choice of D.choices)for(const claimed of[false,true])for(const[tab,quest]of[['earth-homecoming','story'],['equipment','earth-homecoming']]){
  const f=fixture();accepted(f,'home-return');f.sim.state.earthHomecoming.choice=choice.id;f.sim.state.earthHomecoming.claimed=claimed;f.place(D.giver);f.rpg.tab=tab;f.rpg.quest=quest;const before=JSON.stringify(f.sim.state);
  assert.ok(f.ui.point());assert.match(f.ui.context(),/Oren/);assert.equal(f.api.recognition(f.sim,'oren').length,1);assert.ok(f.api.recognition(f.sim,'oren')[0].text.includes(claimed?'paid the account once':'payment is waiting'));assert.equal(f.api.recognition(f.sim,'vessa').length,0);
  assert.equal(f.ui.interact(),true);assert.equal(commands(f).length,0);assert.equal(JSON.stringify(f.sim.state),before);f.place(step('return-verified'));assert.equal(f.api.recognition(f.sim,'oren').length,0);assert.ok(f.api.recognition(f.sim,'vessa')[0].text.includes(choice.id==='public-watch'?'public watch':'reviewed custody'));
  if(claimed){assert.ok(f.ui.point());f.ui.tick();assert.equal(f.rpg.quest,'story');assert.equal(f.rpg.tab,'earth-homecoming');assert.ok(f.ui.point());}
  f.rpg.tab='equipment';f.rpg.quest='story';assert.equal(f.ui.point(),null);assert.equal(f.ui.context(),null);assert.equal(f.ui.interact(),false);assert.equal(f.api.recognition(f.sim,'vessa').length,1);
 }
});
test('a claimed comparator alone still lists the actual missing Confluence account',()=>{const raw=seed();raw.cosmosCampaign.claimed=false;const f=fixture(H.validateWorld(raw));assert.deepEqual(Array.from(f.api.prerequisites(f.sim.state),p=>p.title),[CC.definition.title]);});
test('retained past choices show only actual saved choice names without changing old owners',()=>{const f=fixture(),before=JSON.stringify(f.sim.state),p=f.ui.panel();for(const term of['Darric’s cart road','Prepare managed coppice','License · transfer the named-crew docket','Broadened activation','Limited ·','Public mechanical account','Lower ·'])assert.ok(p.html.includes(term),term);assert.equal(JSON.stringify(f.sim.state),before);assert.equal(commands(f).length,0);});
test('journal, map, tracker and ordinary walk create no campaign or payment facts',()=>{const f=fixture();f.place(D.giver);const before=JSON.stringify(f.sim.state);f.ui.journal();f.ui.page('earth-homecoming');f.api.legend(f.sim);f.ui.tick();f.action('walk','giver');assert.equal(commands(f).length,0);assert.ok(f.calls.some(c=>c.kind==='walk'));assert.equal(JSON.stringify(f.sim.state),before);});
test('acceptance carries captured identity/revision and requires the actual physical giver',()=>{const f=fixture();f.place(D.giver);f.ui.panel();f.action('accept');assert.equal(commands(f).length,1);assert.deepEqual(commands(f)[0].payload,{quest:D.id,expectedActive:f.ctx.active,expectedRevision:f.sim.state.adventure.revision});const other=fixture();other.place(step('bridge-record'));other.ui.panel();other.action('accept');assert.equal(commands(other).length,0);});
test('stale pages refuse changed active/state/context/revision/room/position owners',()=>{for(const change of[f=>f.ctx.active='other',f=>f.ctx.revision++,f=>f.ctx.sim={...f.sim},f=>f.sim.state=copy(f.sim.state),f=>f.sim.state.adventure.revision++,f=>f.sim.room=D.room,f=>f.sim.state.player.x+=.02]){const f=fixture();f.place(D.giver);f.ui.panel();change(f);f.action('accept');assert.equal(commands(f).length,0);assert.ok(f.calls.some(c=>c.kind==='toast'));}});
test('away routes identify the actual current marker and accepted Earth crossing, never a cross-room Walk',()=>{const f=fixture();accepted(f);f.place(D.giver);let ps=f.api.routePoints(f.sim);assert.equal(ps[0].id,'road-gate');assert.equal(ps[0].x,W.GATE.x);assert.equal(ps[0].z,W.GATE.z);assert.ok(f.ui.panel().html.includes('Read Earth crossing and arrival'));f.action('walk','bridge-record');assert.equal(f.calls.filter(c=>c.kind==='walk').length,0);f.action('walk','road-gate');assert.equal(f.calls.filter(c=>c.kind==='walk').length,1);f.sim.room='world-hell';f.sim.returnPos={x:11,z:9,yaw:0};f.sim.state.player={x:0,z:31,yaw:0};ps=f.api.routePoints(f.sim);const real= W.definition('hell').points.find(p=>p.kind==='return');assert.equal(ps[0].x,real.x);assert.equal(ps[0].z,real.z);assert.equal(commands(f).length,0);});
test('available physical steps have local Walk links while optional prep never displaces main tracking',()=>{const f=fixture();accepted(f,'inspect-claim');f.place(step('inspect-claim'));f.rpg.quest='earth-homecoming';f.ui.tick();assert.equal(f.nodes.get('#tracked-detail').textContent,step('west-relay-isolated').name);assert.ok(Array.from(f.api.routePoints(f.sim),p=>p.id).includes('supplied-screen'));f.action('walk','west-relay-isolated');assert.equal(commands(f).length,0);});
test('manual defeat, unavailable work and remote home-arrival cannot dispatch facts',()=>{const f=fixture();accepted(f,'challenge-regent');f.place(step('challenge-regent'));f.ui.panel();f.action('step','regent-repelled');f.action('step','home-return');f.action('defeat','regent-repelled');assert.equal(commands(f).length,0);assert.ok(!f.ui.panel().html.includes('data-rpg="earth-homecoming-step" data-id="regent-repelled"'));});
test('deliberate physical work dispatches its exact step and refusal leaves the workspace',()=>{const f=fixture();accepted(f);f.place(step('bridge-record'));f.ui.panel();f.action('step','bridge-record');assert.equal(commands(f).length,1);assert.equal(commands(f)[0].payload.step,'bridge-record');assert.ok(f.calls.some(c=>c.kind==='paint'));assert.ok(!f.calls.some(c=>c.kind==='close'));});
test('a reported successful physical challenge closes the workspace without the UI granting fight facts',()=>{const f=fixture();accepted(f,'east-relay-isolated');f.place(step('challenge-regent'));const before=JSON.stringify(f.sim.state);f.rpg.api.earthHomecomingCommand=(type,payload)=>{f.calls.push({kind:'command',type,payload:{...payload}});return{ok:true,text:'Synthetic adapter success only; no history changed.'};};f.ui.panel();f.action('step','challenge-regent');assert.equal(commands(f).length,1);assert.ok(f.calls.some(c=>c.kind==='close'));assert.equal(JSON.stringify(f.sim.state),before);});
test('aftermath preview and cancel are pure; confirm binds the exact choice and checkpoint',()=>{for(const c of D.choices){const f=fixture();accepted(f,'passage-secured');f.place(step('aftermath'));const before=JSON.stringify(f.sim.state);f.ui.panel();f.action('review',c.id);assert.equal(commands(f).length,0);assert.equal(f.ui.pending.choice,c.id);assert.ok(f.ui.panel().html.includes('Confirm the junction aftermath'));f.action('cancel');assert.equal(f.ui.pending,null);f.ui.panel();f.action('review',c.id);f.ui.panel();f.action('confirm',c.id);assert.equal(commands(f).length,1);assert.equal(commands(f)[0].type,'choose');assert.equal(commands(f)[0].payload.choice,c.id);assert.equal(JSON.stringify(f.sim.state),before);}});
test('a moved/stale preview or confirmation of the other aftermath cannot imply consent',()=>{for(const change of[f=>f.ctx.active='other',f=>f.sim.state.adventure.revision++,f=>f.sim.state.player.x+=.02]){const f=fixture();accepted(f,'passage-secured');f.place(step('aftermath'));f.ui.panel();f.action('review','public-watch');change(f);f.ui.panel();f.action('confirm','public-watch');assert.equal(commands(f).length,0);}const f=fixture();accepted(f,'passage-secured');f.place(step('aftermath'));f.ui.panel();f.action('review','public-watch');f.ui.panel();f.action('confirm','reviewed-custody');assert.equal(commands(f).length,0);});
test('bridge verification, immediate free return, real home-return and payment have separate route and command gates',()=>{const f=fixture();accepted(f,'return-verified');f.place(step('return-verified'));const html=f.ui.panel().html;assert.ok(html.includes('data-rpg="world-return" data-id="">Return to Firstlight now · free</button>'));assert.ok(!html.includes('Read the free return to Firstlight'));assert.equal(f.api.routePoints(f.sim)[0].id,'road-gate');f.action('claim');assert.equal(commands(f).length,0);f.place(D.giver);f.ui.panel();assert.ok(f.ui.panel().html.includes('earth-homecoming-step" data-id="home-return"'));assert.ok(!f.ui.panel().html.includes('data-rpg="earth-homecoming-claim"'));f.action('step','home-return');assert.equal(commands(f).at(-1).payload.step,'home-return');accepted(f,'home-return');f.ui.panel();f.action('claim');assert.equal(commands(f).at(-1).type,'claim');assert.ok(f.ui.panel().html.includes('completed account waiting'));});
test('current-person lines are physically gated and paid/unpaid language matches saved facts',()=>{const f=fixture();accepted(f,'home-return');f.place(D.giver);assert.ok(f.api.recognition(f.sim,'oren')[0].text.includes('payment is waiting'));f.sim.state.earthHomecoming.claimed=true;assert.ok(f.api.recognition(f.sim,'oren')[0].text.includes('paid the account once'));assert.equal(f.api.recognition(f.sim,'vessa').length,0);f.place(step('return-verified'));assert.ok(f.api.recognition(f.sim,'vessa')[0].text.includes('public watch'));const p={...W.definition('earthlands').points.find(p=>p.id==='merren'),room:D.room};f.place(p);assert.ok(f.api.recognition(f.sim,'merren')[0].text.includes('passage is safe'));});
test('unrelated pages never rebind consent; completed tracker returns to the ordinary story',()=>{const f=fixture();assert.equal(f.ui.page('equipment'),null);assert.equal(f.ui.binding,null);accepted(f,'home-return');f.sim.state.earthHomecoming.claimed=true;f.rpg.quest='earth-homecoming';f.ui.tick();assert.equal(f.rpg.quest,'story');});

test('unaccepted and wrong-scene art is empty and cannot produce support or progress',()=>{const f=fixture();let out=empty();f.art.draw(out,f.sim);assert.equal(all(out).length,0);accepted(f);f.sim.room='mine';out=empty();const before=JSON.stringify(f.sim.state);f.art.draw(out,f.sim);assert.equal(all(out).length,0);assert.equal(JSON.stringify(f.sim.state),before);});
test('accepted apparatus is finite, modest, appearance-only and responds only to recorded work',()=>{const f=fixture();accepted(f,'inspect-claim');f.place(step('inspect-claim'));const before=JSON.stringify(f.sim.state),out=empty();f.art.draw(out,f.sim);assert.ok(all(out).length>10&&all(out).length<45);assert.ok(all(out).some(p=>p.earthHomecomingPart==='folded-warning-signal'));for(const p of all(out)){assert.ok(p.p.every(Number.isFinite));assert.ok(Array.from(p.m).every(Number.isFinite));assert.equal(p.appearanceOnly,true);assert.equal(p.cameraSolid,false);assert.equal(p.cutaway,false);}assert.equal(JSON.stringify(f.sim.state),before);f.sim.state.earthHomecoming.steps.push('supplied-screen');const fitted=empty();f.art.draw(fitted,f.sim);assert.ok(all(fitted).some(p=>p.earthHomecomingPart==='fitted-warning-signal'));assert.ok(!all(fitted).some(p=>p.earthHomecomingPart==='folded-warning-signal'));});
test('every transformed Regent vertex is grounded and stays within the real .65 body radius',()=>{for(const yaw of[0,.4,Math.PI/2,2.1]){const f=fixture(),e=actor(f);e.yaw=yaw;const out=empty(),before=JSON.stringify({state:f.sim.state,e});const frame=f.art.drawEnemy(out,f.sim,e);assert.equal(frame.x,e.x);assert.equal(frame.z,e.z);assert.ok(all(out).some(p=>p.earthHomecomingPart==='regent-split-crown'));let min=Infinity;for(const{kind,p}of parts(out))for(const v of vertices(kind,p)){min=Math.min(min,v[1]);assert.ok(v[1]>=1.57-1e-5);assert.ok(Math.hypot(v[0]-e.x,v[2]-e.z)<=e.radius+1e-5);}assert.ok(Math.abs(min-1.57)<1e-5);assert.equal(JSON.stringify({state:f.sim.state,e}),before);assert.ok(all(out).length<30);}});
test('real installed lock produces exact broad and narrow lines in the actor-owned frame',()=>{for(const distance of[3,10.5]){const f=fixture(),e=actor(f);f.sim.state.player={x:e.x,z:e.z-distance,yaw:0};const frame=H.lock(f.sim,e);assert.ok(frame);e.mode='windup';const out=empty();f.art.drawEnemy(out,f.sim,e);const warns=parts(out).filter(v=>v.p.earthHomecomingTelegraph);assert.equal(warns.length,8);assert.equal(frame.length,distance===3?4:11);for(const{kind,p}of warns)for(const v of vertices(kind,p)){const l=local(frame,v);assert.ok(Math.abs(l.x)<=frame.halfWidth+1e-5);assert.ok(l.z>=-1e-5&&l.z<=frame.length+1e-5);assert.ok(v[1]>1.69);}}});
test('synthetic clipped-frame boundary includes zero and very short lengths without protruding caps',()=>{for(const length of[0,.001,.02,.04,.08,2.7])for(const yaw of[0,.4,Math.PI/2]){const f=fixture(),e=actor(f),s=Object.freeze({kind:'line',x:e.x,z:e.z,yaw,length,halfWidth:.55,pattern:'false-shelter'});e.strike=s;e.mode='windup';const out=empty();f.art.drawEnemy(out,f.sim,e);const warns=parts(out).filter(v=>v.p.earthHomecomingTelegraph);assert.equal(warns.length,length?8:0);for(const{kind,p}of warns)for(const v of vertices(kind,p)){const l=local(s,v);assert.ok(l.z>=-1e-5&&l.z<=length+1e-5,JSON.stringify({length,yaw,l}));assert.ok(Math.abs(l.x)<=.55+1e-5);}}});
test('actual fixed annulus shows both boundaries inside its locked radii and preserves the quiet center',()=>{const f=fixture(),e=actor(f);e.hp=56;f.sim.state.player={x:e.x,z:e.z+3,yaw:0};const s=H.lock(f.sim,e);assert.equal(s.kind,'annulus');assert.equal(H.strikeContains(e,{x:e.x,z:e.z+1.1}),false);e.mode='windup';const out=empty();f.art.drawEnemy(out,f.sim,e);const warns=parts(out).filter(v=>v.p.earthHomecomingTelegraph);assert.equal(warns.length,192);for(const{kind,p}of warns)for(const v of vertices(kind,p)){const radius=Math.hypot(v[0]-s.x,v[2]-s.z);assert.ok(radius>=s.innerRadius-1e-5&&radius<=s.outerRadius+1e-5);assert.ok(v[1]>1.69);}assert.ok(warns.some(v=>v.p.earthHomecomingPart.startsWith('quiet-inner-rim')));assert.ok(warns.some(v=>v.p.earthHomecomingPart.startsWith('danger-outer-rim')));});
test('wrong/stale actor identity or recorded repulse cannot draw an active body or warning',()=>{const f=fixture(),e=actor(f);for(const fake of[{...e},{...e,earthHomecoming:'foreign'}]){const out=empty();assert.equal(f.art.drawEnemy(out,f.sim,fake),false);assert.equal(all(out).length,0);}f.sim.state.earthHomecoming.steps.push('regent-repelled');const out=empty();assert.equal(f.art.drawEnemy(out,f.sim,e),false);assert.equal(all(out).length,0);});
test('paused/reduced-motion and both camera settings keep identical owned warning and geometry',()=>{const f=fixture(),e=actor(f);f.sim.state.player={x:e.x,z:e.z+3,yaw:0};H.lock(f.sim,e);e.mode='windup';const first=empty();f.art.drawEnemy(first,f.sim,e);for(const mode of['follow','tactical']){f.sim.paused=true;f.sim.state.settings.reducedMotion=true;f.sim.state.settings.cameraMode=mode;const out=empty();assert.ok(f.art.drawEnemy(out,f.sim,e));assert.equal(JSON.stringify(out),JSON.stringify(first));}assert.equal(H.canDamage(f.sim,e),false);});
test('after each saved aftermath one road trace and a later modest home trace persist without fake bodies',()=>{for(const choice of D.choices){const f=fixture();accepted(f,'aftermath');f.sim.state.earthHomecoming.choice=choice.id;f.place(step('aftermath'));let out=empty();f.art.draw(out,f.sim);assert.equal(new Set(all(out).filter(p=>p.earthHomecomingTrace).map(p=>p.earthHomecomingTrace)).size,1);assert.ok(!all(out).some(p=>p.earthHomecomingActor));const name=choice.id==='public-watch'?'public-checked-record':'detached-core-cover';assert.ok(all(out).some(p=>p.earthHomecomingPart===name));f.place(D.giver);out=empty();f.art.draw(out,f.sim);assert.equal(all(out).length,0);accepted(f,'home-return');f.sim.state.earthHomecoming.choice=choice.id;const before=JSON.stringify(f.sim.state),home=empty();f.art.draw(home,f.sim);assert.ok(all(home).length<=5&&all(home).length>0);assert.ok(all(home).every(p=>p.earthHomecomingTrace==='home'));assert.equal(JSON.stringify(f.sim.state),before);}});
test('both transformed home accounts rest exactly on the real workshop table and clear every existing nearby box',t=>{
 // Actual WorldArt generates the existing surfaces; this CPU collector replaces
 // GPU batching only. It does not create a game collider or pretend to be pixels.
 const ctx={RealmEngine:E,RealmCore:C,RealmCreative:load('creative.js')};vm.runInNewContext(fs.readFileSync(R+'/src/world.js','utf8'),ctx);
 const engine={clear(){},batch(kind,items,dynamic,opts){return{kind,items,dynamic,...opts};}},world=new ctx.RealmArt.WorldArt(engine);
 const table=world.map.box.find(p=>p.p[0]===12.5&&p.p[1]===2.05&&p.p[2]===8&&p.s[0]===.95&&p.s[1]===.16&&p.s[2]===1.6);assert.ok(table,'actual right workshop table');
 const tableVertices=vertices('box',{...table,m:E.M.compose(...table.p,...table.s)}),bounds={minX:Math.min(...tableVertices.map(v=>v[0])),maxX:Math.max(...tableVertices.map(v=>v[0])),minZ:Math.min(...tableVertices.map(v=>v[2])),maxZ:Math.max(...tableVertices.map(v=>v[2])),top:Math.max(...tableVertices.map(v=>v[1]))};
 assert.ok(Math.abs(bounds.top-2.13)<1e-5);assert.equal(W.height(null,12.5,8.55),1.57,'room-only world fallback is not this table surface');
 const boxBounds=p=>{const vs=vertices('box',{...p,m:p.m||E.M.compose(...p.p,...p.s,...(p.r||[0,0,0]))});return{minX:Math.min(...vs.map(v=>v[0])),maxX:Math.max(...vs.map(v=>v[0])),minY:Math.min(...vs.map(v=>v[1])),maxY:Math.max(...vs.map(v=>v[1])),minZ:Math.min(...vs.map(v=>v[2])),maxZ:Math.max(...vs.map(v=>v[2]))};};
 const nearby=world.map.box.filter(p=>p!==table&&Math.abs(p.p[0]-12.5)<=p.s[0]/2+2&&Math.abs(p.p[2]-8.55)<=p.s[2]/2+2).map(boxBounds),overlap=(a,b)=>a.minX<b.maxX-1e-5&&a.maxX>b.minX+1e-5&&a.minY<b.maxY-1e-5&&a.maxY>b.minY+1e-5&&a.minZ<b.maxZ-1e-5&&a.maxZ>b.minZ+1e-5;
 for(const choice of D.choices){const f=fixture();accepted(f,'home-return');f.sim.state.earthHomecoming.choice=choice.id;f.place(D.giver);const before=JSON.stringify(f.sim.state),out=empty();f.art.draw(out,f.sim);const points=parts(out).flatMap(({kind,p})=>vertices(kind,p));
  assert.ok(points.length>0);const minY=Math.min(...points.map(v=>v[1]));assert.ok(Math.abs(minY-bounds.top)<1e-5,'footplate bottom rests on actual table top');
  for(const v of points){assert.ok(v[0]>=bounds.minX-1e-5&&v[0]<=bounds.maxX+1e-5);assert.ok(v[2]>=bounds.minZ-1e-5&&v[2]<=bounds.maxZ+1e-5);assert.ok(v[1]>=bounds.top-1e-5);}
  const minZ=Math.min(...points.map(v=>v[2])),maxZ=Math.max(...points.map(v=>v[2])),tool=world.map.box.find(p=>p.p[0]===12.5&&p.p[1]===2.22&&p.p[2]===8&&p.s[2]===.61);assert.ok(tool);assert.ok(minZ>tool.p[2]+tool.s[2]/2,'account begins after the actual tool stack ends');
  for(const{p}of parts(out))assert.ok(!nearby.some(b=>overlap(boxBounds(p),b)),'trace part overlaps existing world box: '+p.earthHomecomingPart);assert.equal(JSON.stringify(f.sim.state),before);
  t.diagnostic(JSON.stringify({choice:choice.id,anchor:{x:12.5,z:8.55},tableTop:bounds.top,minimumY:minY,maximumY:Math.max(...points.map(v=>v[1])),minX:Math.min(...points.map(v=>v[0])),maxX:Math.max(...points.map(v=>v[0])),minZ,maxZ,existingBoxClearanceChecks:nearby.length}));
 }
});
test('combined static/body/ring budget is bounded with actual procedural triangle counts',t=>{const f=fixture(),e=actor(f);e.hp=56;f.sim.state.player={x:e.x,z:e.z+3,yaw:0};H.lock(f.sim,e);e.mode='windup';const out=empty();f.art.draw(out,f.sim);f.art.drawEnemy(out,f.sim,e);assert.ok(all(out).length<=260);const triangles=parts(out).reduce((n,{kind})=>n+E.geometry(kind).length/18,0),batches=Object.values(out).filter(v=>v.length).length;assert.ok(triangles<=3200);assert.ok(batches<=2);t.diagnostic(JSON.stringify({projectionItems:all(out).length,triangles,batches}));});
test('styling provides narrow layouts, keyboard focus and reduced-motion without source changes',()=>{const css=fs.readFileSync(R+'/src/earth-homecoming.css','utf8');for(const term of['max-width:600px',':focus-visible','prefers-reduced-motion','min-height:2.7rem'])assert.ok(css.includes(term));for(const[p,h]of Object.entries(hashes))assert.equal(sha(p),h,p);});
