'use strict';
// Synthetic boundary fixtures, separate from the command-earned playable journey.
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),A=require('../src/adventure.js'),H=require('../src/heaven-campaign.js'),R=require('../src/realm-trails.js'),T=require('../src/combat.js');
const D=H.definition,copy=structuredClone,step=id=>D.steps.find(s=>s.id===id);
function seed(){const s=C.fresh();s.adventure.started=true;s.adventure.owned=['trail_blade','travel_coat'];s.adventure.equipment={weapon:'trail_blade',armor:'travel_coat',charm:null};const old=R.definition(D.prerequisite),r=s.realmTrails.records[old.id];r.accepted=true;r.claimed=true;r.steps=R.required(old);return C.validate(s);}
function fixture(raw=seed()){const sim=new C.Simulation(raw);sim.returnPos={...raw.player};sim.room=D.room;let stored=null;const save=s=>{stored=C.validate(s);return{ok:true};};sim.heavenCampaignSave=save;const ctx=()=>({sim,active:'synthetic-boundary',revision:1});const act=(type,p={},io={save})=>H.command(ctx(),type,{quest:D.id,expectedRevision:sim.state.adventure.revision,expectedActive:ctx().active,...p},io);const at=p=>{sim.state.player={...p,yaw:0};};return{sim,save,ctx,act,at,get stored(){return stored;}};}
function history(f,ids,choice=null){f.sim.state.heavenCampaign=H.validate({version:1,accepted:true,steps:ids,choice,claimed:false});}
const beforeWatch=['witness-account','compare-arrival-marks','inspect-false-relay'];
const beforeEscort=[...beforeWatch,'begin-watch','beam-disabled','relay-disabled','secure-service-route'];
test('absence adds only empty optional Heaven history and malformed/future histories refuse',()=>{const old=seed();delete old.heavenCampaign;old.adventure.xp=9999;old.notes=[{text:'synthetic notebook retained',day:1}];const out=C.validate(old);assert.deepEqual(out.heavenCampaign,H.fresh());const without=copy(out);delete without.heavenCampaign;assert.deepEqual(without,old);for(const bad of[null,{...H.fresh(),version:2},{...H.fresh(),steps:['wayfarer-arrived']},{...H.fresh(),choice:'accessible-assist'},{...H.fresh(),claimed:true},{...H.fresh(),escortProgress:99}])assert.throws(()=>H.validate(bad));});
test('acceptance needs claimed Broken Choir and exact owner/revision; refusal changes nothing',()=>{const f=fixture();f.at(D.giver);const before=f.sim.snapshot();for(const p of[{expectedActive:'other'},{expectedRevision:-1}])assert.equal(f.act('accept',p).ok,false);assert.equal(f.act('accept',{}, {save:()=>({ok:false,error:'synthetic refusal'})}).ok,false);assert.deepEqual(f.sim.snapshot(),before);assert.ok(f.act('accept').ok);assert.equal(H.runtime(f.sim).escort.phase,'idle');assert.deepEqual([H.runtime(f.sim).escort.x,H.runtime(f.sim).escort.z],[-29,-69]);f.sim.state.realmTrails.records[D.prerequisite]=R.fresh().records[D.prerequisite];assert.throws(()=>C.validate(f.sim.snapshot()));});
test('manual defeat/arrival and unprepared invitation cannot manufacture history',()=>{const f=fixture();f.at(D.giver);assert.ok(f.act('accept').ok);const before=f.sim.snapshot();for(const id of['beam-disabled','relay-disabled','wayfarer-arrived','invite-wayfarer']){f.at(step(id));assert.equal(f.act('step',{step:id}).ok,false);}assert.equal(f.act('escort-invite').ok,false);assert.deepEqual(f.sim.snapshot(),before);assert.equal(H.enemies(f.sim).length,0);});
test('two locked attacks differ and grounded mirror lengthens only beam warning',()=>{const f=fixture();history(f,[...beforeWatch,'begin-watch']);A.syncScene(f.sim);const beam=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign);f.at({x:beam.x,z:beam.z+2});H.lock(f.sim,beam);const frame=copy(beam.strike);assert.equal(frame.kind,'beam');assert.equal(beam.windup,1.2);assert.equal(beam.recovery,1.7);assert.ok(H.strikeContains(beam,{x:frame.x,z:frame.z+8.9}));assert.equal(H.strikeContains(beam,{x:frame.x+1.1,z:frame.z+2}),false);f.at({x:beam.x+5,z:beam.z});assert.deepEqual(beam.strike,frame);f.sim.state.heavenCampaign.steps.push('ground-mirror');H.lock(f.sim,beam);assert.equal(beam.windup,1.6);assert.equal(beam.recovery,1.7);history(f,[...beforeWatch,'begin-watch','beam-disabled','ground-mirror']);A.syncScene(f.sim);const relay=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign);H.lock(f.sim,relay);assert.equal(relay.strike.kind,'pulse');assert.equal(relay.windup,1.4);assert.equal(relay.recovery,2);assert.ok(H.strikeContains(relay,{x:relay.x+3.5,z:relay.z}));assert.equal(H.strikeContains(relay,{x:relay.x+3.7,z:relay.z}),false);});
test('real damage in windup is accepted, actual defeat saves once and no legacy loot is produced',()=>{const f=fixture();history(f,[...beforeWatch,'begin-watch']);A.syncScene(f.sim);const e=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign),before=f.sim.snapshot();e.mode='windup';e.timer=1;assert.equal(H.canDamage(f.sim,{...e}),false);A.damageEnemy(f.sim,e,5,'weapon');assert.equal(e.hp,105);assert.equal(T.runtime(f.sim).hits.length,1);f.sim.heavenCampaignSave=()=>({ok:false,error:'synthetic defeat refusal'});A.damageEnemy(f.sim,e,999,'weapon');assert.equal(e.hp,1);assert.deepEqual(f.sim.snapshot(),before);f.sim.heavenCampaignSave=f.save;A.damageEnemy(f.sim,e,999,'weapon');assert.equal(e.hp,0);assert.ok(f.sim.state.heavenCampaign.steps.includes('beam-disabled'));assert.deepEqual(f.sim.state.adventure.defeated,before.adventure.defeated);assert.deepEqual(f.sim.state.adventure.drops,before.adventure.drops);assert.equal(f.sim.state.adventure.xp,before.adventure.xp);A.syncScene(f.sim);assert.equal(A.runtime(f.sim).enemies.filter(e=>e.heavenCampaign).length,1);assert.equal(A.runtime(f.sim).enemies.find(e=>e.heavenCampaign).id,D.enemies[1].id);});
test('courier is one owned real actor, waits out of range and unfinished reload resets only its walk',()=>{const f=fixture();history(f,beforeEscort);f.at(step('invite-wayfarer'));assert.ok(f.act('escort-invite').ok);const e=H.runtime(f.sim).escort;assert.equal(e.phase,'following');const origin=copy(e);f.at({x:7,z:17});for(let i=0;i<50;i++)f.sim.tick(.05);assert.deepEqual([e.x,e.z],[origin.x,origin.z]);assert.equal(e.phase,'lagging');assert.equal(f.sim.state.heavenCampaign.steps.includes('wayfarer-arrived'),false);const reloaded=fixture(f.sim.snapshot());const waiting=H.runtime(reloaded.sim).escort;assert.equal(waiting.phase,'idle');assert.deepEqual([waiting.x,waiting.z],[-29,-69]);assert.equal(H.escortStatus(reloaded.sim).phase,'reset');assert.ok(reloaded.sim.state.heavenCampaign.steps.includes('invite-wayfarer'));reloaded.at(step('invite-wayfarer'));assert.ok(reloaded.act('escort-invite').ok);assert.equal(H.runtime(reloaded.sim).escort.phase,'following');});
test('courier completes every supported segment before actual arrival and save refusal remains retryable',()=>{const f=fixture();history(f,beforeEscort);f.at(step('invite-wayfarer'));assert.ok(f.act('escort-invite').ok);const e=H.runtime(f.sim).escort;let attempts=0;f.sim.heavenCampaignSave=()=>{attempts++;return{ok:false,error:'synthetic arrival refusal'};};for(let i=0;i<2200&&e.phase!=='awaiting-save';i++){f.at({x:e.x,z:e.z});f.sim.tick(.05);}assert.equal(e.phase,'awaiting-save');assert.equal(e.routeIndex,D.escort.route.length);assert.equal(f.sim.state.heavenCampaign.steps.includes('wayfarer-arrived'),false);assert.deepEqual([e.x,e.z],[7,17]);f.at({x:7,z:17});const priorAttempts=attempts;for(let i=0;i<10;i++)f.sim.tick(.05);assert.equal(attempts,priorAttempts,'persistent refusal is not retried each frame');f.sim.heavenCampaignSave=f.save;for(let i=0;i<12;i++)f.sim.tick(.05);assert.equal(e.phase,'arrived');assert.ok(f.sim.state.heavenCampaign.steps.includes('wayfarer-arrived'));assert.deepEqual(f.stored.heavenCampaign,f.sim.state.heavenCampaign);const r=fixture(f.sim.snapshot());assert.equal(H.runtime(r.sim).escort.phase,'arrived');assert.deepEqual([H.runtime(r.sim).escort.x,H.runtime(r.sim).escort.z],[7,17]);});
test('whole claim is atomic across costs/capacity/refusal and repeat IDs cannot pay twice',()=>{for(const key of['coins','ore','wood','fiber','refused']){const f=fixture();history(f,D.steps.filter(s=>!s.optional).map(s=>s.id),'accessible-assist');f.at(D.giver);if(key==='coins'||key==='ore')f.sim.state.adventure[key]=9999;else if(key!=='refused')f.sim.state.sandbox.inventory[key]=999;const before=f.sim.snapshot();assert.equal(f.act('claim',{},key==='refused'?{save:()=>({ok:false,error:'synthetic capacity-era refusal'})}:{save:f.save}).ok,false);assert.deepEqual(f.sim.snapshot(),before);if(key==='coins'||key==='ore')f.sim.state.adventure[key]=0;else if(key!=='refused')f.sim.state.sandbox.inventory[key]=0;f.sim.state.adventure.xp=9999;const balances=f.sim.snapshot();assert.ok(f.act('claim').ok);assert.equal(f.sim.state.adventure.xp,9999);assert.equal(f.sim.state.adventure.coins-balances.adventure.coins,16);assert.equal(f.sim.state.adventure.ore-balances.adventure.ore,3);assert.equal(f.sim.state.adventure.hp,balances.adventure.hp);assert.deepEqual(f.sim.state.adventure.equipment,balances.adventure.equipment);const paid=f.sim.snapshot();assert.equal(f.act('claim',{request:'changed-request'}).duplicate,true);assert.deepEqual(f.sim.snapshot(),paid);}});
test('welcome is explicit and lasting; activation is short transient ordinary use with no payout',()=>{const f=fixture();history(f,D.steps.filter(s=>!s.optional&&s.id!=='arrangement'&&s.id!=='verify-welcome').map(s=>s.id));f.at(step('arrangement'));assert.ok(f.act('choose',{choice:'broadened-activation'}).ok);assert.equal(f.act('choose',{choice:'accessible-assist'}).ok,false);const before=f.sim.snapshot();assert.ok(f.act('activate').ok);assert.equal(H.runtime(f.sim).activation.active,true);assert.deepEqual(f.sim.snapshot(),before);assert.equal(f.act('activate').ok,false);f.sim.paused=true;for(let i=0;i<40;i++)f.sim.tick(.05);assert.equal(H.runtime(f.sim).activation.active,true);f.sim.paused=false;for(let i=0;i<25;i++)f.sim.tick(.05);assert.equal(H.runtime(f.sim).activation.active,false);assert.equal(f.act('activate').ok,false);for(let i=0;i<50;i++)f.sim.tick(.05);assert.ok(f.act('activate').ok);assert.deepEqual(f.sim.state.heavenCampaign,before.heavenCampaign);assert.equal(f.sim.state.adventure.coins,before.adventure.coins);});
test('the real lock clips its entire beam width against existing cover and keeps art/contact identical',()=>{const f=fixture();history(f,[...beforeWatch,'begin-watch']);A.syncScene(f.sim);const e=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign);e.x=0;e.z=-1;f.at({x:0,z:-10});assert.ok(H.lock(f.sim,e));assert.ok(e.strike.length>3.4&&e.strike.length<3.5);assert.equal(H.beamLength(f.sim,e),e.strike.length);assert.equal(H.strikeContains(e,{x:0,z:-10}),false);assert.equal(H.strikeContains(e,{x:0,z:-3}),true);const locked=copy(e.strike);f.at({x:9,z:-1});assert.deepEqual(e.strike,locked);e.x=2.3;e.z=-1;f.at({x:2.3,z:-10});assert.ok(A.visible(f.sim,e,f.sim.state.player),'centerline clears the instrument');H.lock(f.sim,e);assert.ok(e.strike.length<3.5,'the beam edge still meets the real instrument');assert.equal(H.strikeContains(e,{x:2.3,z:-10}),false);});
test('real arrow collision accepts a winding-up Heaven apparatus and reports one actual killing impact',()=>{const AR=require('../src/arsenal.js'),f=fixture();history(f,[...beforeWatch,'begin-watch']);f.sim.state.adventure.owned.push('trail_bow');f.sim.state.adventure.equipment.weapon='trail_bow';A.syncScene(f.sim);const e=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign);f.at({x:e.x,z:e.z+4});e.mode='windup';e.timer=10;e.hp=1;assert.ok(f.sim.adventureCommand('synthetic-heaven-arrow','attack',{target:e.id}).ok);AR.update(f.sim,.2);assert.equal(e.hp,0);assert.deepEqual(A.runtime(f.sim).fx.filter(v=>v.kind.startsWith('arrow-')).map(v=>v.kind),['arrow-hit']);assert.equal(T.runtime(f.sim).hits.length,1);assert.ok(f.sim.state.heavenCampaign.steps.includes('beam-disabled'));});
test('real leave resets an unfinished courier before immediate re-entry; saved invitation stays intact',()=>{const f=fixture();history(f,beforeEscort);f.at(step('invite-wayfarer'));assert.ok(f.act('escort-invite').ok);const old=H.runtime(f.sim).escort;for(let i=0;i<20;i++)f.sim.tick(.05);assert.notEqual(old.z,D.escort.z);assert.ok(f.sim.leave().ok);f.sim.returnPos={...f.sim.state.player};f.sim.room=D.room;const current=H.runtime(f.sim).escort;assert.notStrictEqual(current,old);assert.equal(current.phase,'idle');assert.deepEqual([current.x,current.z],[-29,-69]);assert.ok(f.sim.state.heavenCampaign.steps.includes('invite-wayfarer'));});
test('production adventure drawing preserves owned campaign matrices and contributes no generic warning',()=>{
 require('../src/engine.js');const art=require('../src/heaven-campaign-art.js');require('../src/adventure-art.js');
 for(const resolved of[false,true]){
  const f=fixture();history(f,[...beforeWatch,'begin-watch',...(resolved?['beam-disabled']:[])]);A.syncScene(f.sim);
  const e=A.runtime(f.sim).enemies.find(e=>e.heavenCampaign);f.at({x:e.x+1,z:e.z+2});
  f.sim.tick(.05);assert.equal(e.mode,'windup');e.timer=.7;
  const empty=()=>({box:[],octa:[],disc:[],round:[],cylinder:[]}),pure=empty(),integrated=empty();
  art.drawEnemy(pure,f.sim,e,12);globalThis.RealmAdventureArt.draw(integrated,f.sim,12);
  for(const kind of Object.keys(pure))assert.deepEqual(integrated[kind].filter(p=>p.heavenCampaignActor===e.id),pure[kind],kind+' owned matrices and positions unchanged');
  assert.ok(Object.values(integrated).flat().filter(p=>p.em===.75&&p.c===0xd098c8).length===0,'no second generic ring warning');
  assert.equal(T.threat(f.sim),null);T.runtime(f.sim).target=e.id;assert.equal(T.threat(f.sim).kind,resolved?'garden-pulse':'garden-beam');
 }
});
test('courier gait follows actual supported distance and quiet settings retain a grounded stance',()=>{
 require('../src/engine.js');const art=require('../src/heaven-campaign-art.js'),E=require('../src/engine.js'),f=fixture();history(f,beforeEscort);f.at(step('invite-wayfarer'));assert.ok(f.act('escort-invite').ok);
 const e=H.runtime(f.sim).escort;for(let i=0;i<10;i++)f.sim.tick(.05);assert.ok(e.walking&&e.distance>0);
 const empty=()=>({box:[],octa:[],disc:[],round:[]}),moving=empty(),quiet=empty(),paused=empty();art.drawEscort(moving,f.sim,e,0);f.sim.state.settings.reducedMotion=true;art.drawEscort(quiet,f.sim,e,999);f.sim.state.settings.reducedMotion=false;f.sim.paused=true;art.drawEscort(paused,f.sim,e,999);assert.deepEqual(quiet,paused);assert.notDeepEqual(moving,quiet);assert.ok(moving.box.filter(p=>p.heavenCampaignPart==='courier-foot').every(p=>p.p[1]>=1.57+.095));
 for(const[k,parts]of Object.entries(moving))for(const p of parts){const geometry=E.geometry(k);for(let i=0;i<geometry.length;i+=6){const v=E.M.transform(p.m,Array.from(geometry.slice(i,i+3)));assert.ok(v[1]>=1.57-1e-5,'moving courier stays grounded');assert.ok(Math.hypot(v[0]-e.x,v[2]-e.z)<=D.escort.radius+1e-5,'moving pose stays in actual courier body');}}
});
