'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),H=require('../src/home-history.js'),L=require('../src/local-life.js'),RT=require('../src/realm-trails.js'),X=require('../src/creative.js'),Art=require('../src/home-history-art.js');
const copy=structuredClone;
// These fixed-step regressions retain the exact original four commissions.
// The supplied carrier has separate physical-authority tests and stays fresh here.
const D=require('../src/earth-consignment-data.js');
const OLD_IDS=Object.freeze(['heaven-propagation-bed-v1','hell-refuge-water-v1','atlantis-bellglass-lamp-v1','cosmos-drawing-shelf-v1']);
assert.deepEqual(D.OLD_IDS,OLD_IDS,'canonical legacy membership cannot drift');
assert.deepEqual(L.definitions.map(d=>d.id),[...OLD_IDS,D.ID],'five-job catalogue is exact');
const LEGACY_DEFINITIONS=Object.freeze(OLD_IDS.map(id=>{const d=L.definition(id);assert.ok(d,'missing original commission '+id);return d;}));
const assertFreshConsignment=state=>assert.deepEqual(state.localLife.records[D.ID],D.freshRecord(),'legacy coverage leaves the separate supplied commission fresh');
/* Explicit synthetic boundaries, distinct from the command-earned journeys. */
function fixture(){const s=C.fresh();s.adventure.started=true;
 for(const d of LEGACY_DEFINITIONS){if(d.prerequisite){const old=RT.definition(d.prerequisite),r=s.realmTrails.records[old.id];r.accepted=r.claimed=true;r.steps=old.steps.map(s=>s.id);if(old.escort){r.checkpoint=old.escort.route.length-1;r.assisted=true;}}s.localLife.records[d.id]={accepted:true,claimed:true,choice:d.choices[0].id,steps:d.steps.map(s=>s.id)};}
 s.bridgeCommunity={version:1,accepted:true,choice:'shelter',steps:['fittings','fit','inspect'],claimed:true};
 Object.assign(s.sandbox.inventory,{wood:9,stone:9,fiber:9,crystal:9});s.player={x:12,z:9,yaw:0};assertFreshConsignment(s);const sim=new C.Simulation(s),writes=[];assertFreshConsignment(sim.state);
 const io={save:s=>{writes.push(C.validate(s));return{ok:true};}},act=(type,payload={},saver=io)=>H.command({sim},type,{expectedRevision:H.layoutAction(type)?sim.state.retreat.revision:sim.state.homeHistory.revision,...payload},saver);return{sim,writes,io,act};
}
function home(h,kind,slot='n'){const layout=copy(h.sim.state.retreat);layout.items=layout.items.filter(i=>i.slot!==slot&&i.kind!==kind);layout.items.push({kind,slot,rotation:0});return layout;}
test('absent homeHistory migrates to empty v1 without replaying claimed knowledge or prior fields',()=>{const h=fixture(),raw=h.sim.snapshot();delete raw.homeHistory;const before=copy(raw),s=C.validate(raw);assert.deepEqual(raw,before);assert.deepEqual(s.homeHistory,H.fresh());for(const k of Object.keys(raw))assert.deepEqual(s[k],raw[k],k);assert.equal(s.version,9);assert.equal(s.adventure.version,12);assert.equal(s.retreat.version,1);});
test('null, future, unknown, duplicate and malformed ledgers refuse instead of clearing',()=>{for(const raw of[null,{...H.fresh(),version:2},{...H.fresh(),revision:-1},{...H.fresh(),owned:['invented']},{...H.fresh(),owned:['memory-farroad','memory-farroad']},{...H.fresh(),pinned:'invented'}])assert.throws(()=>H.validate(raw));});
test('a prior acceptance or complete unpaid work never grants ownership',()=>{const h=fixture(),d=H.definitions[0];for(const claimed of[false]){h.sim.state.localLife.records[d.quest].claimed=claimed;assert.equal(h.act('craft',{kind:d.id}).ok,false);h.sim.state.homeHistory.owned=[d.id];assert.throws(()=>C.validate(h.sim.state));}});
test('pin is independent of equipment projects and accepting story or work',()=>{const sim=new C.Simulation(),before=sim.snapshot();assert.ok(H.command({sim},'pin',{kind:'memory-bellglass',expectedRevision:0},{save:()=>({ok:true})}).ok);assert.equal(sim.state.homeHistory.pinned,'memory-bellglass');for(const k of Object.keys(before).filter(k=>!['homeHistory','journal','nextEvent'].includes(k)))assert.deepEqual(sim.state[k],before[k],k);const after=sim.snapshot();assert.equal(H.command({sim},'pin',{kind:'memory-farroad',expectedRevision:0},{save:()=>({ok:true})}).ok,false);assert.deepEqual(sim.snapshot(),after);});
for(const d of H.definitions){
 test(d.id+' validates costs before spending and saves before adopting once-only ownership',()=>{const h=fixture(),initial=h.sim.snapshot(),player=h.sim.state.player,adventure=h.sim.state.adventure,sandbox=h.sim.state.sandbox;
  assert.equal(h.act('craft',{kind:d.id},{save:()=>({ok:false,error:'synthetic quota refusal'})}).ok,false);assert.deepEqual(h.sim.snapshot(),initial);
  assert.equal(h.act('craft',{kind:d.id},{save:()=>{throw Error('write failure');}}).ok,false);assert.deepEqual(h.sim.snapshot(),initial);
  assert.equal(h.act('craft',{kind:d.id},{save:()=>Promise.resolve({ok:true})}).ok,false);assert.deepEqual(h.sim.snapshot(),initial);
  assert.ok(h.act('craft',{kind:d.id}).ok);assert.equal(h.writes.length,1);for(const[k,n]of Object.entries(d.cost))assert.equal(h.sim.state.sandbox.inventory[k],initial.sandbox.inventory[k]-n);
  assert.equal(h.sim.state.player,player);assert.equal(h.sim.state.adventure,adventure);assert.equal(h.sim.state.sandbox,sandbox);assert.deepEqual(h.sim.state.retreat,initial.retreat);
  for(const k of Object.keys(initial).filter(k=>!['homeHistory','sandbox','journal','nextEvent'].includes(k)))assert.deepEqual(h.sim.state[k],initial[k],k);
  const made=h.sim.snapshot();assert.equal(h.act('craft',{kind:d.id,request:'new-request'}).duplicate,true);assert.deepEqual(h.sim.snapshot(),made);const cold=new C.Simulation(made);assert.equal(H.command({sim:cold},'craft',{kind:d.id,expectedRevision:cold.state.homeHistory.revision},{save:()=>({ok:true})}).duplicate,true);assert.deepEqual(cold.snapshot(),made);
 });
 test(d.id+' missing material, wrong bench, paused/dead owner and stale revision leave exact state',()=>{for(const alter of[h=>h.sim.state.sandbox.inventory[Object.keys(d.cost)[0]]=0,h=>h.sim.state.player={x:2.5,z:6,yaw:0},h=>h.sim.paused=true,h=>h.sim.state.adventure.hp=0]){const h=fixture();alter(h);const before=h.sim.snapshot();assert.equal(h.act('craft',{kind:d.id}).ok,false);assert.deepEqual(h.sim.snapshot(),before);}const h=fixture(),before=h.sim.snapshot();assert.equal(h.act('craft',{kind:d.id,expectedRevision:77}).ok,false);assert.deepEqual(h.sim.snapshot(),before);});
 test(d.id+' unowned and duplicate placements reject through save, direct decorate and forged history',()=>{const h=fixture();assert.throws(()=>C.validate({...h.sim.snapshot(),retreat:home(h,d.id)}));assert.equal(h.sim.act('unowned','decorate',{home:home(h,d.id),expectedRevision:0}).ok,false);
  h.sim.homeUndo.push(home(h,d.id));assert.equal(h.sim.act('forged-history','layout-undo').ok,false);assert.equal(h.sim.homeUndo.length,1);h.sim.homeUndo=[];assert.ok(h.act('craft',{kind:d.id}).ok);
  const layout=home(h,d.id);layout.items.push({slot:'sw',kind:d.id,rotation:0});assert.equal(h.act('decorate',{home:layout}).ok,false);assert.throws(()=>C.validate({...h.sim.snapshot(),retreat:layout}));
 });
 test(d.id+' deliberate move/remove and undo/redo save refusal keep history and costs atomic',()=>{const h=fixture();h.act('craft',{kind:d.id});const initial=h.sim.snapshot();assert.ok(h.act('decorate',{home:home(h,d.id)}).ok);assert.equal(h.sim.homeUndo.length,1);const placed=h.sim.snapshot(),undo=copy(h.sim.homeUndo),redo=copy(h.sim.homeRedo);
  assert.equal(h.act('layout-undo',{}, {save:()=>({ok:false,error:'another writer'})}).ok,false);assert.deepEqual(h.sim.snapshot(),placed);assert.deepEqual(h.sim.homeUndo,undo);assert.deepEqual(h.sim.homeRedo,redo);
  assert.ok(h.act('layout-undo').ok);assert.deepEqual(h.sim.state.retreat.items,initial.retreat.items);assert.ok(h.act('layout-redo').ok);assert.deepEqual(h.sim.state.retreat.items,placed.retreat.items);
  assert.ok(h.act('decorate',{home:home(h,d.id,'sw')}).ok);assert.equal(h.sim.state.retreat.items.filter(i=>i.kind===d.id).length,1);assert.equal(h.sim.state.retreat.items.find(i=>i.kind===d.id).slot,'sw');
  const layout=copy(h.sim.state.retreat);layout.items=layout.items.filter(i=>i.kind!==d.id);assert.ok(h.act('decorate',{home:layout}).ok);assert.ok(h.sim.state.homeHistory.owned.includes(d.id));assert.deepEqual(h.sim.state.sandbox.inventory,placed.sandbox.inventory);
  const cold=new C.Simulation(h.sim.snapshot());assert.ok(cold.state.homeHistory.owned.includes(d.id));assert.equal(cold.homeUndo.length,0);
 });
 test(d.id+' original geometry is bounded by its declared floor footprint in all rotations',()=>{let count=0;for(let rotation=0;rotation<4;rotation++){const parts=[],angle=rotation*Math.PI/2;assert.ok(Art.draw(d.id,(kind,x,y,z,w,h,depth,c,opt)=>parts.push({kind,x,y,z,w,h,depth,c,opt})));assert.ok(parts.length>=7);for(const p of parts){assert.equal(p.opt.homeMemoryKind,d.id);assert.ok([p.x,p.y,p.z,p.w,p.h,p.depth].every(Number.isFinite));assert.ok(p.y-p.h/2>=1.55-.01);const rx=Math.abs(p.x*Math.cos(angle)+p.z*Math.sin(angle)),rz=Math.abs(-p.x*Math.sin(angle)+p.z*Math.cos(angle));/* yaw swaps the footprint; x/z extent conservatively includes local tilt */const ex=p.w/2,ez=p.depth/2+Math.abs(Math.sin(p.opt.r?.[0]||0))*p.h/2;assert.ok(rx+(rotation%2?ez:ex)<= (rotation%2?d.d:d.w)/2+.012,d.id+' width');assert.ok(rz+(rotation%2?ex:ez)<=(rotation%2?d.w:d.d)/2+.012,d.id+' depth');}count+=parts.length;}assert.ok(count>=28);assert.equal(X.FURNITURE[d.id].w,d.w);});
}
test('inside placement uses actual body position while durable snapshot keeps its home checkpoint',()=>{const h=fixture(),d=H.definitions[0];h.act('craft',{kind:d.id});h.sim.room='retreat';h.sim.returnPos={x:37,z:0,yaw:0};h.sim.state.player={x:0,z:-2.7,yaw:0};const before=h.sim.snapshot();assert.equal(h.act('decorate',{home:home(h,d.id)}).ok,false);assert.deepEqual(h.sim.snapshot(),before);assert.equal(h.sim.homeUndo.length,0);h.sim.state.player={x:0,z:3.5,yaw:Math.PI};const player=h.sim.state.player;assert.ok(h.act('decorate',{home:home(h,d.id)}).ok);assert.equal(h.sim.state.player,player);assert.deepEqual(h.writes.at(-1).player,h.sim.returnPos);assert.equal(h.sim.room,'retreat');});
test('one of each occupies four chosen slots with no extra power or campaign payout',()=>{const h=fixture(),before=copy(h.sim.state.adventure);for(const [i,d]of H.definitions.filter(d=>d.source!=='bridgeCommunity').entries()){assert.ok(h.act('craft',{kind:d.id}).ok);assert.ok(h.act('decorate',{home:home(h,d.id,['n','sw','se','w'][i])}).ok);}assert.equal(h.sim.state.homeHistory.owned.length,4);assert.deepEqual(h.sim.state.adventure,before);assert.deepEqual(C.validate(h.sim.snapshot()),h.sim.snapshot());});
test('pending placement cannot transfer to another character with identical ownership and revision',()=>{const UI=require('../src/home-history-ui.js'),a=fixture(),b=fixture(),id='memory-cuttings';a.act('craft',{kind:id});b.act('craft',{kind:id});let active=a.sim,writes=0;const notices=[],e={get sim(){return active;},selectedSlot:'n'},hooks={renderPanel:()=>{},toast:t=>notices.push(t),homeCommand:()=>{writes++;},redrawRoom:()=>{}};const w=new UI.Workspace(e,hooks);w.pending={owner:a.sim,kind:id,slot:'n',revision:0};active=b.sim;const before=b.sim.snapshot();assert.equal(w.action({dataset:{action:'memory-place'}}),true);assert.equal(writes,0);assert.deepEqual(b.sim.snapshot(),before);assert.equal(w.pending,null);assert.match(notices[0],/character changed/);w.pending={owner:a.sim,kind:id,slot:'n',revision:0};w.render();assert.equal(w.pending,null);});
