'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const art=require('../src/mill-gate-art.js');
const base=1.5;
function leaf(done){const out={box:[],round:[],'timber-panel':[]},state={done};const prior=structuredClone(state);const gate=art.draw(out,state.done,base);assert.deepEqual(state,prior);return{gate,out};}
test('gate lift is a pure projection of the existing saved repair',()=>{const before=leaf(false),after=leaf(true);assert.equal(before.gate.lift,0);assert.equal(after.gate.lift,.74);assert.ok(Math.abs(after.gate.center[1]-before.gate.center[1]-.74)<1e-12);assert.deepEqual(before,leaf(false));assert.deepEqual(after,leaf(true));});
test('five separated timber planks have positive connected transforms and vertical grain',()=>{for(const done of[false,true]){const {gate,out}=leaf(done);assert.equal(out['timber-panel'].length,5);const zs=[];for(const p of out['timber-panel']){const m=p.m;assert.ok(m[1]>0&&m[6]>0&&m[8]>0);assert.ok(Math.abs(m[1]*m[6]*m[8]-p.s[0]*p.s[1]*p.s[2])<1e-8);assert.deepEqual(Array.from(m.slice(12,15)),p.p.map(Math.fround));assert.equal(p.p[1],gate.center[1]);zs.push(p.p[2]);}assert.ok(zs.every((z,i)=>!i||z-zs[i-1]>.19));}});
test('jammed and repaired hardware differ without becoming navigation or camera authorities',()=>{const b=leaf(false).out,a=leaf(true).out;assert.ok(b.box.some(i=>i.millPart==='jammed-brace'));assert.ok(!a.box.some(i=>i.millPart==='jammed-brace'));assert.ok(a.box.some(i=>i.millPart==='repair-brace'));for(const out of[b,a])for(const i of Object.values(out).flat()){assert.equal(i.cameraSolid,false);assert.equal(i.cutaway,true);assert.ok(i.p.every(Number.isFinite));assert.ok(i.s.every(n=>Number.isFinite(n)&&n>0));}});
test('rack stays engaged with the fixed pinion in both leaf positions',()=>{for(const done of[false,true]){const rack=leaf(done).out.box.find(i=>i.millPart==='lift-rack'),pinion=base+1.79;assert.ok(pinion>=rack.p[1]-rack.s[1]/2&&pinion<=rack.p[1]+rack.s[1]/2);}});
test('fixed frame stays around the established bank anchor with three mapped members',()=>{const items=[],a={add(kind,x,y,z,w,h,d,c,opt){items.push({kind,p:[x,y,z],s:[w,h,d],...opt});},beam(from,to,w,c,opt){items.push({kind:'beam',from,to,...opt});}};art.frame(a,base);assert.equal(items.filter(i=>i.kind==='timber-panel').length,3);assert.equal(items.filter(i=>i.millPart==='upright').length,2);for(const i of items){assert.equal(i.cameraSolid??false,false);if(i.p)assert.ok(Math.abs(i.p[0]-art.ANCHOR.x)<=.5&&Math.abs(i.p[2]-art.ANCHOR.z)<=.66);}});
test('gate projection remains bounded to 29 moving parts and five timber instances',()=>{for(const done of[false,true]){const all=Object.values(leaf(done).out).flat();assert.ok(all.length<=29);assert.equal(all.filter(i=>i.millPart==='leaf-plank').length,5);}});
