'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const S=require('../src/soundscape.js');
function harness(){const nodes=[],param=()=>({value:0,calls:[],setTargetAtTime(...args){this.calls.push(args);}}),node=type=>{const n={type,gain:param(),frequency:param(),Q:param(),connections:[],starts:0,stops:0,disconnects:0,connect(o){this.connections.push(o);return o;},start(){this.starts++;},stop(){this.stops++;},disconnect(){this.disconnects++;}};nodes.push(n);return n;};const ctx={currentTime:2,sampleRate:8000,createGain:()=>node('gain'),createBiquadFilter:()=>node('filter'),createBufferSource:()=>node('buffer'),createOscillator:()=>node('oscillator'),createBuffer:(channels,length,rate)=>({channels,length,rate,data:new Float32Array(length),getChannelData(){return this.data;}})},master=node('master'),graph=new S.Soundscape(ctx,master,()=>.75);return{nodes,ctx,master,graph};}
test('the original immutable room profiles are separate from state and services',()=>{const context={module:{exports:{}}};for(const name of ['AudioContext','document','localStorage','fetch'])Object.defineProperty(context,name,{get(){throw Error(name+' unexpectedly accessed');}});vm.runInNewContext(fs.readFileSync(require.resolve('../src/soundscape.js'),'utf8'),context);assert.ok(Object.isFrozen(S.PROFILES));for(const p of Object.values(S.PROFILES))assert.ok(Object.isFrozen(p));});
test('five roads and actual Atlantis body medium have honest distinct atmosphere',()=>{for(const[room,medium,id]of[['world-heaven',null,'heaven'],['world-hell',null,'hell'],['world-earthlands',null,'coast'],['cosmos-near-expanse',null,'cosmos'],['world-atlantis','air','atlantis'],['world-atlantis','water','submerged']])assert.equal(S.project({room,medium}).profile.id,id);assert.equal(S.project({room:'retreat'}).profile.id,'interior');assert.equal(S.project({room:null}).profile.id,'field');});
test('quiet state is driven by pause hidden page or actual death while retaining profile identity',()=>{for(const state of [{paused:true},{hidden:true},{hp:0},{hp:-1}]){const p=S.project({room:'world-heaven',...state});assert.equal(p.quiet,true);assert.equal(p.profile.id,'heaven');assert.equal(p.birds,false);}assert.equal(S.project({hp:1}).quiet,false);});
test('only living visible daytime outdoor Earth can chirp; no birds underground or in cosmic realms',()=>{for(const room of ['world-heaven','world-hell','world-atlantis','cosmos-near-expanse','mine','retreat'])assert.equal(S.project({room,hour:12}).birds,false);for(const hour of [0,5.99,20.01,23])assert.equal(S.project({hour}).birds,false);for(const hour of [6,12,20])assert.equal(S.project({hour}).birds,true);});
test('bounded graph creates exactly one noise loop and three voices connected only to its own bus',()=>{const h=harness();assert.equal(h.graph.noise.buffer.length,24000);assert.ok(h.graph.noise.buffer.data.every(v=>Math.abs(v-.06)<1e-6));assert.equal(h.graph.voices.length,3);assert.equal(h.nodes.reduce((n,p)=>n+p.starts,0),4);assert.deepEqual(h.graph.bus.connections,[h.master]);assert.equal(h.graph.bus.gain.value,0);});
test('room transitions schedule a new local mix once, with no per-frame allocation or master mutation',()=>{const h=harness(),count=h.nodes.length;h.graph.update({room:'world-hell'},0);assert.equal(h.graph.filter.frequency.calls.length,1);for(let i=1;i<20;i++)h.graph.update({room:'world-hell'},i*.05);assert.equal(h.nodes.length,count);assert.equal(h.graph.filter.frequency.calls.length,1);assert.equal(h.master.gain.calls.length,0);assert.equal(h.graph.voices[0].oscillator.frequency.calls[0][0],65.405);h.graph.update({room:'world-heaven'},1);assert.equal(h.graph.filter.frequency.calls.length,2);});
test('pause and hidden changes fade the bus without stopping or replacing composed music master',()=>{const h=harness();h.graph.update({},0);h.graph.update({paused:true},.1);assert.equal(h.graph.bus.gain.calls.at(-1)[0],0);h.graph.update({hidden:true},.2);assert.equal(h.master.disconnects,0);assert.equal(h.master.stops,0);h.graph.update({},.3);assert.equal(h.graph.bus.gain.calls.at(-1)[0],1);});
test('bird cadence requires continuous elapsed frames and never backfills through reload or hidden gaps',()=>{const h=harness();assert.equal(h.graph.update({},0).bird,false);for(let t=.1;t<8;t+=.1)assert.equal(h.graph.update({},t).bird,false);assert.equal(h.graph.update({},8.01).bird,true);assert.equal(h.graph.update({},8.02).bird,false);assert.equal(h.graph.update({},40).bird,false);assert.equal(h.graph.update({},0).bird,false);assert.equal(h.graph.update({room:'world-hell'},.1).bird,false);});
test('disposal retires every owned loop and connection once and fences later updates',()=>{const h=harness();h.graph.update({},0);h.graph.dispose();h.graph.dispose();assert.equal(h.graph.snapshot().loopSources,0);assert.equal(h.nodes.filter(n=>n.starts).reduce((sum,n)=>sum+n.stops,0),4);assert.equal(h.master.disconnects,0);assert.deepEqual(h.graph.update({},8),{disposed:true,bird:false});assert.equal(h.graph.bus.disconnects,1);});
test('profile projection does not change caller state or allocate audio authority',()=>{const input={room:'world-atlantis',medium:'water',hp:34,paused:false,hour:17},before=JSON.stringify(input);assert.deepEqual(S.project(input),S.project({...input}));assert.equal(JSON.stringify(input),before);assert.throws(()=>new S.Soundscape(null,null,null),TypeError);});
