"""Actual new-region UI and production rules in isolated software Chromium.
Accelerated walking/depth probes are labelled; they do not measure human feel or GPU speed.
"""
from pathlib import Path
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
import hashlib,json,tempfile,threading,traceback
from playwright.sync_api import sync_playwright
from browser_support import chromium_launch_kwargs
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'evidence10/world-foundations-browser';OUT.mkdir(parents=True,exist_ok=True)
report={'method':__doc__,'checks':[],'browser_errors':[],'html_sha256':hashlib.sha256((ROOT/'index.html').read_bytes()).hexdigest(),'errors':[]}
class Handler(SimpleHTTPRequestHandler):
 def __init__(self,*a,**kw):super().__init__(*a,directory=str(ROOT),**kw)
 def log_message(self,*a):pass
def check(name,ok):
 report['checks'].append({'name':name,'passed':bool(ok)});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok:raise AssertionError(name)
server=ThreadingHTTPServer(('127.0.0.1',0),Handler);threading.Thread(target=server.serve_forever,daemon=True).start();url=f'http://127.0.0.1:{server.server_port}/'
try:
 with tempfile.TemporaryDirectory(prefix='firstlight-world-foundations-') as profile,sync_playwright() as pw:
  context=pw.chromium.launch_persistent_context(profile,**chromium_launch_kwargs(),viewport={'width':1280,'height':800});page=context.new_page();page.on('pageerror',lambda e:report['browser_errors'].append(str(e)));page.add_init_script('window.__ETERNITIES_TEST_MODE=true;window.__ETERNITIES_CAPTURE_MODE=true;')
  response=page.goto(url,wait_until='load');page.wait_for_function('window.Realm');check('exact offline build loads',hashlib.sha256(response.body()).hexdigest()==report['html_sha256'])
  ev=lambda js,arg=None:page.evaluate(js,arg);state=lambda:ev('Realm.state');scene=lambda:ev('Realm.diagnostics.scene')
  def render():ev("()=>{Realm.test.quality('low');Realm.test.render()}")
  def close():
   if page.locator('#rpg-window').evaluate('(e)=>e.open'):page.locator('#rpg-close').click()
  def walk(x,z):
   close();r=ev('([x,z])=>{const r=Realm.test.move(x,z);if(!r.ok)return r;for(let i=0;i<12000&&Realm.test.path.length;i++)Realm.test.step(.05);Realm.test.render();const p=Realm.diagnostics.adventure.player;return{ok:Math.hypot(p.x-x,p.z-z)<.25}}',[x,z]);check(f'production walk reaches {x},{z}',r.get('ok'))
  def open_world(id):
   close();page.keyboard.press('j');page.locator('[data-rpg="open"][data-id="worlds"]').click();page.locator('[data-rpg="world-list"]').click() if page.locator('[data-rpg="world-list"]').count() else None;page.locator('[data-rpg="world-select"][data-id="'+id+'"]').click()
  def enter(id,normal_time=False):
   open_world(id);text=page.locator('#rpg-content').inner_text();check(id+' terms show objectives, kit requirement, exact rewards and free return',all(s in text for s in ['Declared payout','expedition kit','XP','Return','Equipment remains your choice']))
   page.locator('[data-rpg="world-preview"]').click();check(id+' has explicit crossing confirmation',page.locator('[data-rpg="world-confirm"]').count()==1);before=state();page.locator('[data-rpg="world-confirm"]').click();render();after=state()
   if normal_time:
    check(id+' normal crossing preserves ownership while its clock runs',all(after[k]==before[k] for k in ['journeys','notes','score','scoreRevision','retreat','visitor']) and all(after['adventure'][k]==v for k,v in before['adventure'].items() if k!='elapsed'))
   else:check(id+' crossing preserves canonical saved state',after==before)
   check(id+' physically supported scene opens',ev('(id)=>Realm.diagnostics.world?.id===id',id))
   if id=='cosmos':check('Roads Cosmos has one presentation owner',page.locator('#world-home').is_visible() and not page.locator('#cosmos-home').is_visible() and page.locator('#cosmos-labels span').count()==0)
  render();walk(11,9);check('initial kit is command-earned before any chapter',ev("Realm.test.adventure('browser-world-kit','start')")['ok']);walk(18,6);initial_kit=state()
  # The earlier pier remains a separate interaction, and remote invitations cannot travel.
  close();walk(0,27);page.keyboard.press('e');render();check('Lantern Pier rest remains independent',scene()=='valley' and not page.locator('#rpg-window').evaluate('(e)=>e.open'));open_world('heaven');check('remote invitation cannot cross',page.locator('[data-rpg="world-preview"]').count()==0);close();walk(18,6)
  for id in ['heaven','hell','earthlands','atlantis','cosmos']:
   enter(id);page.locator('#tracked-open').click();check(id+' tracked opening reads its local work before acceptance','Declared payout' in page.locator('#rpg-content').inner_text() and state()['journeys']['realms'][id]['active'] is None);close();d=ev('(id)=>RealmWorldFoundations.definition(id)',id);giver=next(p for p in d['points'] if p['id']==d['quest']['giverId']);walk(giver['x'],giver['z']);open_world(id);old=state();page.locator('[data-rpg="world-accept"]').click();render();check(id+' explicit UI accepts first run without paying',state()['journeys']['realms'][id]['active']['run']==1 and state()['adventure']['coins']==old['adventure']['coins']);close()
   for index,o in enumerate(d['quest']['objectives']):
    p=next(p for p in d['points'] if p['id']==o['pointId']);walk(p['x'],p['z']);open_world(id);page.locator('[data-rpg="world-observe"][data-id="'+o['id']+'"]').click();render();check(id+' UI records objective '+o['id'],o['id'] in state()['journeys']['realms'][id]['active']['observed']);close()
    if index==0:
     saved=state();page.reload();page.wait_for_function('window.Realm');render();check(id+' native reload retains partial work at home checkpoint',scene()=='valley' and state()['journeys']==saved['journeys']);enter(id)
   walk(giver['x'],giver['z']);open_world(id);coins=state()['adventure']['coins'];weapon=state()['adventure']['equipment']['weapon'];page.locator('[data-rpg="world-claim"]').click();render();check(id+' UI pays exact first reward once',state()['adventure']['coins']-coins==d['quest']['reward']['coins'] and state()['journeys']['realms'][id]['lastClaim']==1);check(id+' payout never auto-equips',state()['adventure']['equipment']['weapon']==weapon);close();paid=state();r=ev('(id)=>Realm.test.worldCommand("claim",{realm:id,run:1,request:"changed"})',id);check(id+' new request identity cannot duplicate payout',r.get('duplicate') and state()==paid)
   page.keyboard.press('e');render();check(id+' local giver recognizes completed work',d['quest']['completionText'] in page.locator('#rpg-content').inner_text());page.locator('#rpg-content [data-rpg="open"][data-id="atlas"]').click();page.locator('[data-rpg="world-walk"][data-id="'+d['quest']['giverId']+'"]').click();ev('()=>{for(let i=0;i<300&&Realm.test.path.length;i++)Realm.test.step(.05)}');render();player=ev('Realm.diagnostics.adventure.player');check(id+' UI approach leaves a readable conversation distance',.9<((player['x']-giver['x'])**2+(player['z']-giver['z'])**2)**.5<2.8)
   page.keyboard.press('v');render();check(id+' diorama follows supported body',ev('Realm.diagnostics.camera.projection')=='orthographic');page.screenshot(path=str(OUT/(id+'-diorama.png')));page.keyboard.press('v');render();check(id+' third person retains perspective',ev('Realm.diagnostics.camera.projection')=='perspective');page.screenshot(path=str(OUT/(id+'-third.png')))
   ev('Realm.test.worldReturn()');render();check(id+' free return reaches home',scene()=='valley')
  # The original quiet visit stays distinct until work is explicitly accepted.
  close();walk(14,-5);page.keyboard.press('e');render();check('legacy Cosmos invitation remains separate',page.locator('[data-rpg="cosmos-confirm"]').count()==1);before=state();page.locator('[data-rpg="cosmos-confirm"]').click();render();check('legacy entry grants no work consent or payout',state()==before and state()['journeys']['realms']['cosmos']['active'] is None);check('legacy Cosmos retains one original presentation owner',page.locator('#cosmos-home').is_visible() and not page.locator('#world-home').is_visible() and page.locator('#world-labels span').count()==0);walk(3,7);open_world('cosmos');page.locator('[data-rpg="world-accept"]').click();close();render();check('explicit work acceptance hands Cosmos presentation to Roads',state()['journeys']['realms']['cosmos']['active']['run']==2 and page.locator('#world-home').is_visible() and not page.locator('#cosmos-home').is_visible() and page.locator('#cosmos-labels span').count()==0);accepted=state()['journeys']['realms']['cosmos'];page.locator('#world-home').click();render();check('adopted legacy trip returns through its original saved checkpoint',scene()=='valley' and state()['player']==before['player'] and state()['journeys']['realms']['cosmos']==accepted and not page.locator('#world-home').is_visible() and not page.locator('#cosmos-home').is_visible());walk(18,6)
  # Three-dimensional gallery path is optional, with real body/camera medium and dry volumes.
  enter('atlantis');d=ev('RealmWorldFoundations.definition("atlantis")');p=next(p for p in d['points'] if p['id']==d['dive']['entryId']);walk(p['x'],p['z']);page.keyboard.press('e');render();check('gallery invitation declares F/G, hold and no air timer','F ascends' in page.locator('#rpg-content').inner_text() and 'no air timer' in page.locator('#rpg-content').inner_text());page.locator('[data-rpg="world-dive"]').click();render();check('explicit gallery entry creates real depth',ev('Realm.diagnostics.world.dive') is not None)
  def swim_to(x,y,z):
   r=ev('''([x,y,z])=>{for(let i=0;i<1500;i++){const p=Realm.diagnostics.adventure.player,s=Realm.test.worldDiveStatus(),dx=x-p.x,dz=z-p.z,dy=y-s.y;if(Math.hypot(dx,dz)<.12&&Math.abs(dy)<.12)break;Realm.test.worldSwim(Math.hypot(dx,dz)<.12?0:dx,Math.hypot(dx,dz)<.12?0:dz,Math.abs(dy)<.12?0:Math.sign(dy),.025);}Realm.test.render();const p=Realm.diagnostics.adventure.player,s=Realm.test.worldDiveStatus();return{ok:Math.hypot(p.x-x,p.z-z)<.2&&Math.abs(s.y-y)<.2,status:s};}''',[x,y,z]);check(f'production 3D swim reaches {x},{y},{z}',r['ok']);return r
  swim_to(8,-2.4,-25);depth=ev('Realm.test.worldDiveStatus().y');ev('()=>{for(let i=0;i<80;i++)Realm.test.worldSwim(0,0,0,.05)}');check('released depth holds without floating camera authority',ev('Realm.test.worldDiveStatus().y')==depth);ev('Realm.test.view({yaw:0,elevation:-.08,distance:3.5});Realm.test.render()');check('submerged camera is measured independently',ev('Realm.diagnostics.world.dive.camera')=='water');page.screenshot(path=str(OUT/'atlantis-swim.png'))
  page.keyboard.press('v');render();check('gallery diorama retains actual body height and enabled cutaway',ev('Realm.diagnostics.camera.projection')=='orthographic' and ev('Realm.diagnostics.cutaway.enabled') and ev('Realm.test.worldDiveStatus().y')==depth);page.screenshot(path=str(OUT/'atlantis-gallery-diorama.png'));page.keyboard.press('v');render()
  page.keyboard.press('m');check('gallery map explains actual wet lane, air court and depth controls',all(s in page.locator('#rpg-content').inner_text() for s in ['Plan view','wet gallery','air court','F ascends','east wet lane']));check('gallery map offers landmark reading instead of impossible dry walking',page.locator('#rpg-content [data-rpg="world-walk"]').count()==0 and page.locator('#rpg-content [data-rpg="world-inspect"]').count()==2);page.locator('[data-rpg="world-inspect"][data-id="gallery-landing"]').click();check('gallery exit can be inspected without teleporting',scene()=='world-atlantis' and ev('Realm.test.worldDiveStatus().y')==depth and 'Gallery landing' in page.locator('#rpg-content').inner_text());check('wet local work has no dry movement or turn-in actions',page.locator('#rpg-content [data-rpg="world-walk"], #rpg-content [data-rpg="world-accept"], #rpg-content [data-rpg="world-observe"], #rpg-content [data-rpg="world-claim"]').count()==0);page.locator('#rpg-content [data-rpg="open"][data-id="atlas"]').click();page.locator('[data-rpg="world-inspect"][data-id="tide-steps"]').click();check('reading gallery entry while wet offers no second entry',page.locator('#rpg-content [data-rpg="world-dive"]').count()==0 and ev('Realm.test.worldDiveStatus().y')==depth);close()
  swim_to(8,-2.7,-34);check('submerged court has actual air body volume',ev('Realm.diagnostics.world.dive.body')=='air' and ev('Realm.diagnostics.world.dive.dryCourt')=='bellglass-air');page.screenshot(path=str(OUT/'atlantis-air-court.png'));swim_to(8,-2.7,-28);swim_to(12,-1.8,-29);swim_to(12,-1.4,-39.3);page.keyboard.press('e');render();check('gallery landing returns to supported dry quay',ev('Realm.diagnostics.world.dive') is None and ev('()=>{const p=Realm.diagnostics.adventure.player;return RealmWorldFoundations.walkable(Realm.diagnostics.scene,p.x,p.z)}'))
  # Earn a partial repeat, then let real enemy ticks cause a fall. This phase
  # uses accelerated production time; the ordinary keyboard phase below does not.
  ev('Realm.test.worldReturn()');walk(18,6);enter('hell');d=ev('RealmWorldFoundations.definition("hell")');giver=next(p for p in d['points'] if p['id']==d['quest']['giverId']);walk(giver['x'],giver['z']);open_world('hell');page.locator('[data-rpg="world-accept"]').click();close();p=next(p for p in d['points'] if p['id']==d['quest']['objectives'][0]['pointId']);walk(p['x'],p['z']);page.keyboard.press('e');page.locator('[data-rpg="world-observe"][data-id="first"]').click();close();partial=state()['journeys']['realms']['hell'];walk(44,-92.9);ev('()=>{Realm.test.step(60);Realm.test.render()}');check('actual sentinel hits open the fallen dialog',state()['adventure']['hp']==0 and page.locator('#fallen-dialog').evaluate('(e)=>e.open'));view=ev('Realm.diagnostics.camera.preset');page.keyboard.press('v');page.keyboard.press('1');check('fallen dialog consumes camera and attack shortcuts',ev('Realm.diagnostics.camera.preset')==view and not ev('Realm.diagnostics.adventure.tactics.auto') and ev('Realm.diagnostics.adventure.enemies.find(e=>e.id==="hell-salvage-sentinel").hp')==90);page.locator('#revive-button').click();render();check('actual revive returns to the spring and clears the trip',scene()=='valley' and ev('Realm.diagnostics.world') is None and state()['adventure']['hp']==ev('Realm.diagnostics.adventure.stats.maxHP'));check('revive preserves the partial accepted repeat and paid history',state()['journeys']['realms']['hell']==partial);paid=state();page.reload(wait_until='load');page.wait_for_function('window.Realm');render();check('native reload keeps revived home and partial realm work',state()['journeys']==paid['journeys'] and state()['adventure']==paid['adventure'] and state()['player']==paid['player'])
  check('browser has no runtime error',not report['browser_errors'] and not ev('Realm.diagnostics.errors'));context.close()
  # Setup walks below remain accelerated. Only held keys, release, modal pause
  # and camera exchange run through the ordinary requestAnimationFrame loop.
  report['normal_keyboard_phase']='Isolated software browser, real frame/input loop; accelerated walking setup. No GPU or human pace claim.'
  normal=pw.chromium.launch(**chromium_launch_kwargs());page=normal.new_page(viewport={'width':1280,'height':800});page.on('pageerror',lambda e:report['browser_errors'].append(str(e)));page.add_init_script('window.__ETERNITIES_TEST_MODE=true;');page.goto(url);page.wait_for_function('window.Realm');ev('(w)=>Realm.test.replace(w)',initial_kit);render();enter('atlantis',normal_time=True);walk(8,-16);page.keyboard.press('e');page.locator('[data-rpg="world-dive"]').click();ev('Realm.test.view({yaw:0,elevation:.12,distance:5})');check('gallery normal frame loop is unpaused',not ev('Realm.diagnostics.adventure.paused'))
  start=ev('Realm.test.worldDiveStatus().y');page.keyboard.down('g');page.wait_for_function('(y)=>Realm.test.worldDiveStatus().y<y-.8',arg=start);page.keyboard.up('g');down=ev('Realm.test.worldDiveStatus().y');check('G actually descends through production held-key frames',down<start-.8);page.wait_for_timeout(350);check('released G holds physical depth',abs(ev('Realm.test.worldDiveStatus().y')-down)<.001)
  page.keyboard.down('f');page.wait_for_function('(y)=>Realm.test.worldDiveStatus().y>y+.5',arg=down);page.keyboard.up('f');check('F actually ascends through production held-key frames',ev('Realm.test.worldDiveStatus().y')>down+.5)
  before=ev('Realm.diagnostics.adventure.player');page.keyboard.down('w');page.wait_for_function('(z)=>Realm.diagnostics.adventure.player.z<z-.7',arg=before['z']);page.keyboard.up('w');check('W actually swims using camera-relative input',ev('Realm.diagnostics.adventure.player.z')<before['z']-.7)
  page.keyboard.press('j');check('gallery journal pauses simulation',ev('Realm.diagnostics.adventure.paused'));depth=ev('Realm.test.worldDiveStatus().y');view=ev('Realm.diagnostics.camera.preset');page.keyboard.down('g');page.wait_for_timeout(500);page.keyboard.up('g');page.keyboard.press('v');check('modal consumes depth and camera shortcuts',ev('Realm.test.worldDiveStatus().y')==depth and ev('Realm.diagnostics.camera.preset')==view);close();page.keyboard.press('v');page.wait_for_timeout(300);check('camera exchange preserves physical swimmer depth',ev('Realm.diagnostics.camera.preset')!=view and abs(ev('Realm.test.worldDiveStatus().y')-depth)<.001)
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(150);page.keyboard.press('e');page.wait_for_timeout(200);check('compact gallery rejection displays a real transient toast',page.locator('#toast').evaluate('(e)=>e.classList.contains("show")&&Number(getComputedStyle(e).opacity)>.9') and 'Reach the gallery landing' in page.locator('#toast').inner_text());box=page.locator('#world-depth').bounding_box();check('compact depth information stays inside the viewport',box and box['x']>=0 and box['y']>=0 and box['x']+box['width']<=391 and box['y']+box['height']<=844);toast=page.locator('#toast').bounding_box();check('compact depth information and transient toast occupy separate space',box and toast and (box['y']+box['height']<=toast['y'] or toast['y']+toast['height']<=box['y']));page.screenshot(path=str(OUT/'atlantis-normal-keyboard-compact.png'));page.set_viewport_size({'width':1280,'height':800});page.keyboard.press('Escape');check('Escape freely returns swimmer home',scene()=='valley' and ev('Realm.diagnostics.world') is None);check('normal frame controls have no runtime errors',not report['browser_errors'] and not ev('Realm.diagnostics.errors'));report['status']='passed';normal.close()
except Exception:
 report['status']='failed';report['errors'].append(traceback.format_exc());raise
finally:
 server.shutdown();server.server_close();(OUT/'REPORT.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
