/* Labelled synthetic boundary fixtures; earned movement is covered separately. */
'use strict';
const{test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),A=require('../src/adventure.js'),W=require('../src/world-foundations.js');
const AR=require('../src/arsenal.js');
require('../src/combat.js');
const ctx=sim=>({sim,active:'synthetic-world-character',revision:3});
function initial(){const sim=new C.Simulation();sim.state.player={x:11,z:9,yaw:0};assert.ok(sim.adventureCommand('world-boundary-initial-kit','start').ok);sim.state.player={...W.GATE,yaw:0};return sim;}
function enter(id='heaven'){const sim=initial(),ticket=W.preview(ctx(sim),id);assert.ok(ticket.ok);assert.ok(W.enter(ticket.ticket,ctx(sim),{save:()=>({ok:true}),build:()=>{}}).ok);return sim;}
function point(sim,id){const p=W.definition(sim.room).points.find(p=>p.id===id);assert.ok(p);assert.ok(W.walkable(sim.room,p.x,p.z));sim.state.player={x:p.x,z:p.z,yaw:0};}
function act(sim,type,p={},save=()=>({ok:true})){return W.command(ctx(sim),type,{realm:W.definition(sim.room).id,...p},{save});}
function finish(sim){const d=W.definition(sim.room);point(sim,d.quest.giverId);assert.ok(act(sim,'accept').ok);const run=sim.state.journeys.realms[d.id].active.run;for(const o of d.quest.objectives){point(sim,o.pointId);assert.ok(act(sim,'observe',{run,objective:o.id}).ok);}point(sim,d.quest.giverId);return run;}
test('optional journeys migrate old world 9 saves without touching banked XP, choices, home or music',()=>{const raw=C.fresh();delete raw.journeys;raw.adventure.xp=9999;raw.notes=[{text:'Synthetic compatibility note',day:1}];const expected=JSON.parse(JSON.stringify(raw)),s=C.validate(raw);assert.deepEqual(s.journeys,W.fresh());delete s.journeys;assert.deepEqual(s,expected);assert.equal(C.VERSION,9);assert.equal(A.VERSION,11);});
test('new schema rejects forward, malformed, unknown and impossible claim history',()=>{for(const change of [s=>s.version=2,s=>s.realms.extra={},s=>delete s.realms.heaven,s=>s.realms.heaven.lastClaim=1,s=>s.realms.heaven.counter=1,s=>s.realms.heaven.firstClaimed=true,s=>s.realms.heaven.active={run:0,kind:'opening',observed:[]},s=>s.realms.heaven.defeated=['foreign-enemy']]){const s=W.fresh();change(s);assert.throws(()=>W.validate(s));}});
test('five-light gate is supported and separate from existing lake and Cosmos markers',()=>{assert.ok(C.walkable(W.GATE.x,W.GATE.z));const sim=initial();assert.ok(W.atRoad(sim));sim.state.player={x:0,z:27,yaw:0};assert.equal(W.atRoad(sim),false);sim.state.player={x:0,z:23,yaw:0};assert.equal(W.atRoad(sim),false);sim.state.player={x:14,z:-5,yaw:0};assert.equal(W.atRoad(sim),false);});
test('travel checkpoints original state, and rejects changed owner, revision, position or ticket',()=>{for(const kind of ['owner','revision','position','cancel','save','build']){const sim=initial(),t=W.preview(ctx(sim),'heaven').ticket,c=ctx(sim);if(kind==='owner')c.active='another';if(kind==='revision')c.revision++;if(kind==='position')sim.state.player.x+=.5;if(kind==='cancel')W.cancel(t);const before=sim.snapshot();let builds=0;const r=W.enter(t,c,{save:()=>kind==='save'?{ok:false,error:'synthetic quota'}:{ok:true},build:()=>{builds++;if(kind==='build')throw Error('synthetic constructor failure');},restore:()=>{}});assert.equal(r.ok,false,kind);assert.equal(sim.room,null);assert.deepEqual(sim.snapshot(),before);if(kind!=='build')assert.equal(builds,0);}});
test('travel, free return, re-entry and cold reload do not grant or advance accepted work',()=>{const sim=enter(),before=sim.snapshot();assert.deepEqual(before.journeys,W.fresh());assert.ok(W.leave(sim).ok);assert.deepEqual(sim.snapshot(),before);const t=W.preview(ctx(sim),'heaven');assert.ok(W.enter(t.ticket,ctx(sim),{save:()=>({ok:true}),build:()=>{}}).ok);assert.deepEqual(sim.snapshot(),before);const reopened=new C.Simulation(sim.snapshot());assert.equal(reopened.room,null);assert.deepEqual(reopened.snapshot(),before);});
test('accepted objectives require physical arrival and current run; repeats remain once-only',()=>{const sim=enter(),d=W.definition(sim.room);point(sim,d.quest.objectives[0].pointId);assert.equal(act(sim,'observe',{run:1,objective:'first'}).ok,false);assert.equal(act(sim,'accept').ok,false);point(sim,d.quest.giverId);assert.ok(act(sim,'accept').ok);const run=sim.state.journeys.realms.heaven.active.run;assert.equal(act(sim,'observe',{run,objective:'first'}).ok,false);point(sim,d.quest.objectives[0].pointId);assert.equal(act(sim,'observe',{run:run+1,objective:'first'}).ok,false);assert.ok(act(sim,'observe',{run,objective:'first'}).ok);const saved=sim.snapshot();assert.equal(act(sim,'observe',{run,objective:'first'}).duplicate,true);assert.deepEqual(sim.snapshot(),saved);assert.equal(new C.Simulation(saved).state.journeys.realms.heaven.active.observed.length,1);});
test('save refusal and capacity-blocked turn-in preserve completed objectives, currency and journal atomically',()=>{const sim=enter('hell'),run=finish(sim);sim.state.adventure.coins=9999;const blocked=sim.snapshot();assert.equal(act(sim,'claim',{run}).ok,false);assert.deepEqual(sim.snapshot(),blocked);sim.state.adventure.coins=0;const refused=sim.snapshot();assert.equal(act(sim,'claim',{run},()=>({ok:false,error:'synthetic refusal'})).ok,false);assert.deepEqual(sim.snapshot(),refused);assert.equal(act(sim,'claim',{run},()=>{throw Error('synthetic write exception');}).ok,false);assert.deepEqual(sim.snapshot(),refused);assert.ok(act(sim,'claim',{run}).ok);assert.equal(sim.state.journeys.realms.hell.lastClaim,run);});
test('claim fences survive changed request IDs, reload, re-entry and intentional smaller repeat runs',()=>{const sim=enter(),run=finish(sim),before=sim.state.adventure.coins;assert.ok(act(sim,'claim',{run,request:'first'}).ok);const paid=sim.snapshot();assert.equal(sim.state.adventure.coins-before,7);assert.equal(act(sim,'claim',{run,request:'different'}).duplicate,true);assert.deepEqual(sim.snapshot(),paid);assert.equal(sim.state.journal.at(-1).kind,'realm-work');const reload=new C.Simulation(paid);assert.equal(reload.state.journeys.realms.heaven.lastClaim,run);assert.ok(W.enter(W.preview(ctx(reload),'heaven').ticket,ctx(reload),{save:()=>({ok:true}),build:()=>{}}).ok);point(reload,W.definition(reload.room).quest.giverId);assert.equal(act(reload,'claim',{run}).duplicate,true);const second=finish(reload);assert.equal(second,run+1);const reward=act(reload,'claim',{run:second});assert.deepEqual(reward.reward,{xp:5,coins:2,ore:0});assert.equal(reload.state.adventure.coins,paid.adventure.coins+2);assert.equal(act(reload,'claim',{run:second}).duplicate,true);});
test('reward changes only declared fields and retains explicit classes, gear, sockets, XP ceiling and story history',()=>{const sim=enter(),run=finish(sim);sim.state.adventure.xp=9999;const before=JSON.parse(JSON.stringify(sim.state.adventure));assert.ok(act(sim,'claim',{run}).ok);const after=JSON.parse(JSON.stringify(sim.state.adventure));for(const k of ['coins','xp','revision'])delete before[k],delete after[k];assert.deepEqual(after,before);assert.equal(sim.state.adventure.xp,9999);assert.equal(A.level(sim.state.adventure),5);});
test('only canonical local enemies use local defeat records and never enter legacy loot history',()=>{const sim=enter('hell'),d=W.definition(sim.room),e=A.runtime(sim).enemies.find(e=>e.id==='hell-salvage-sentinel');assert.ok(e);const before=JSON.parse(JSON.stringify(sim.state.adventure));assert.equal(W.defeat(sim,{id:'foreign',worldRealm:'hell'}),false);A.damageEnemy(sim,e,1000);assert.equal(e.hp,0);assert.deepEqual(sim.state.journeys.realms.hell.defeated,[e.id]);for(const k of ['defeated','drops','xp','coins','ore'])assert.deepEqual(sim.state.adventure[k],before[k]);const saved=sim.snapshot();assert.ok(C.validate(saved));assert.ok(W.leave(sim).ok);assert.ok(W.enter(W.preview(ctx(sim),'hell').ticket,ctx(sim),{save:()=>({ok:true}),build:()=>{}}).ok);assert.equal(A.runtime(sim).enemies.some(e=>e.id===d.enemies[0].id),false);});
test('copied or live enemies cannot manufacture a defeat, and a real defeat preserves the revision ceiling',()=>{const sim=enter('hell'),e=A.runtime(sim).enemies[0],before=sim.snapshot();assert.equal(W.defeat(sim,{...e,hp:0}),false);assert.equal(W.defeat(sim,e),false);assert.deepEqual(sim.snapshot(),before);sim.state.adventure.revision=1e9;A.damageEnemy(sim,e,1000);assert.equal(sim.state.adventure.revision,1e9);assert.ok(sim.snapshot());});
test('bow targets and actual arrows use new scene ground, while solid cover blocks hits',()=>{const sim=enter('hell'),e=A.runtime(sim).enemies[0];sim.state.adventure.owned.push('trail_bow');assert.ok(sim.adventureCommand('synthetic-world-bow-equip','equip',{id:'trail_bow'}).ok);sim.state.player={x:44,z:-89,yaw:Math.PI};assert.ok(AR.aimClear(sim,sim.state.player,e));assert.ok(sim.adventureCommand('synthetic-world-bow-release','attack',{target:e.id}).ok);for(let i=0;i<8;i++)sim.tick(.05);assert.ok(e.hp<e.maxHP);assert.equal(AR.runtime(sim).arrows.length,0);assert.equal(AR.aimClear(sim,{x:35,z:-88},{x:43,z:-88}),false);});
test('skipped active run identities are rejected rather than inventing an unknown payout history',()=>{const s=W.fresh(),r=s.realms.heaven;r.counter=900;r.lastClaim=1;r.firstClaimed=true;r.active={run:900,kind:'survey',observed:[]};assert.throws(()=>W.validate(s));});
test('failure after scene sync restores the original runtime graph as well as position and room',()=>{const sim=initial();A.runtime(sim);const before=JSON.parse(JSON.stringify(sim.adventureRuntime)),runtime=sim.adventureRuntime,t=W.preview(ctx(sim),'hell').ticket,stop=global.RealmCombat.stop;try{global.RealmCombat.stop=()=>{throw Error('synthetic post-sync fault');};assert.equal(W.enter(t,ctx(sim),{save:()=>({ok:true}),build:()=>{},restore:()=>{}}).ok,false);}finally{global.RealmCombat.stop=stop;}assert.equal(sim.room,null);assert.equal(sim.adventureRuntime,runtime);assert.deepEqual(JSON.parse(JSON.stringify(sim.adventureRuntime)),before);assert.equal(sim.worldTrip,undefined);});
test('every new realm objective can return to its real giver through production navigation',()=>{for(const d of W.definitions().filter(d=>W.handles(d.room))){const giver=d.points.find(p=>p.id===d.quest.giverId);for(const o of d.quest.objectives){const p=d.points.find(p=>p.id===o.pointId),path=C.pathfind(p,giver,{id:d.room});assert.ok(path,d.id+' '+o.id+' return');let a=p;for(const b of path){assert.ok(W.segment(d.room,a,b));a=b;}}}});
test('gallery has actual depth, held release, body/camera medium separation and true blocking air-court walls',()=>{const sim=enter('atlantis'),d=W.definition(sim.room).dive;point(sim,d.entryId);assert.ok(W.diveEnter(sim).ok);assert.equal(sim.moveTo(8,-25).ok,false);const y=sim.worldDive.y;W.swim(sim,0,0,0,1);assert.equal(sim.worldDive.y,y);for(let i=0;i<7;i++)W.swim(sim,0,0,-1,.1);assert.ok(sim.worldDive.y<y);const held=sim.worldDive.y;const air=W.divingStatus(sim,[8,3,-25]),wet=W.divingStatus(sim,[8,-1,-25]);assert.equal(air.camera,'air');assert.equal(wet.camera,'water');assert.equal(sim.worldDive.y,held);assert.equal(W.medium(sim,[8,-1.8,-34]),'air');assert.equal(W.medium(sim,[12,-1.8,-34]),'water');assert.equal(W.swimClear(d,11.38,-2,-34),false);assert.equal(W.swimClear(d,8,-2,-30.62),true);assert.equal(W.swimClear(d,8,-1,-34),false,'full head interval meets air-court ceiling');assert.equal(W.swimClear(d,15,-2,-34),false,'route volume bounds actual movement');const before=sim.snapshot();assert.ok(W.leave(sim).ok);assert.deepEqual(sim.snapshot(),before);assert.equal(sim.worldDive,undefined);});
test('companion menu preserves dry waiting position, and an explicit recall uses the dry entry during a dive',()=>{for(const foreign of [false,true]){const sim=enter('atlantis');sim.state.adventure.companion.bonded=true;sim.state.adventure.companion.mode='stay';point(sim,W.definition(sim.room).dive.entryId);const prior={...A.runtime(sim).companion},quay={...sim.state.player};if(foreign)A.runtime(sim).companion.room='synthetic-previous-room';assert.ok(W.diveEnter(sim).ok);assert.ok(sim.adventureCommand('synthetic-dive-follow','companion-mode',{mode:'follow'}).ok);sim.tick(.1);const fox=A.runtime(sim).companion,expected=foreign?quay:prior;assert.equal(fox.x,expected.x);assert.equal(fox.z,expected.z);assert.equal(W.walkable(sim.room,fox.x,fox.z),true);assert.equal(fox.status,'Waiting on the quay');}});
